/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/saude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar a saúde do processo
         * @description Confirma somente que o processo local da API está disponível.
         */
        get: operations["obter_saude_api_v1_saude_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dados-sinteticos/restauracoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restaurar os dados sintéticos da demonstração
         * @description Repõe o conjunto sintético versionado em uma única transação. Exige o cabeçalho `Idempotency-Key` em toda requisição.
         */
        post: operations["restaurar_api_v1_dados_sinteticos_restauracoes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prontidao/dependencias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar a prontidão das dependências
         * @description Devolve o estado mais recente de backend, banco de dados, INMET e OpenAI. Backend e banco de dados são recomputados a cada chamada; INMET e OpenAI, na primeira consulta, disparam a verificação em segundo plano e retornam 'verificando'.
         */
        get: operations["consultar_api_v1_prontidao_dependencias_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prontidao/dependencias/{nome}/verificacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solicitar uma nova verificação de prontidão
         * @description Solicita, de forma assíncrona e idempotente, uma nova verificação de INMET ou OpenAI. Exige o cabeçalho `Idempotency-Key` em toda requisição. Backend e banco de dados não aceitam este recurso: já são recomputados a cada `GET`.
         */
        post: operations["verificar_novamente_api_v1_prontidao_dependencias__nome__verificacoes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/segurados/padrao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar o segurado sintético padrão
         * @description Devolve o segurado sintético padrão usado na visão de Segurado da demonstração.
         */
        get: operations["consultar_api_v1_segurados_padrao_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meteorologia/coletas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solicitar uma coleta meteorológica manual
         * @description Solicita, de forma idempotente, uma coleta meteorológica manual para a área informada. Exige o cabeçalho `Idempotency-Key` em toda requisição.
         */
        post: operations["solicitar_coleta_api_v1_meteorologia_coletas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meteorologia/{sincronizacao_id}/nova-tentativa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solicitar uma nova tentativa após indisponibilidade
         * @description Solicita, de forma idempotente, uma nova coleta correlacionada à sincronização de origem informada, sem reabrir nem mutar a sincronização/execução anteriores. Exige o cabeçalho `Idempotency-Key` em toda requisição.
         */
        post: operations["solicitar_nova_tentativa_api_v1_meteorologia__sincronizacao_id__nova_tentativa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meteorologia/cenarios-sinteticos/{identificador}/ativar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ativar um cenário sintético de contingência
         * @description Ativa, de forma idempotente, o cenário sintético de contingência informado para a área monitorada indicada. O evento resultante tem `proveniencia = sintetico`, nunca combinado com dados `real_inmet`. Exige o cabeçalho `Idempotency-Key` em toda requisição.
         */
        post: operations["ativar_cenario_sintetico_api_v1_meteorologia_cenarios_sinteticos__identificador__ativar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meteorologia/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar os eventos meteorológicos normalizados
         * @description Devolve os eventos meteorológicos já normalizados, do mais recente.
         */
        get: operations["consultar_eventos_api_v1_meteorologia_eventos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meteorologia/sincronizacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar o histórico de sincronizações meteorológicas
         * @description Devolve a última tentativa, a última coleta válida, a próxima consulta estimada e o histórico completo de sincronizações, só com dados persistidos.
         */
        get: operations["consultar_sincronizacoes_api_v1_meteorologia_sincronizacoes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/execucoes/{execucao_id}/avaliacao-risco": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar o detalhe da decisão de risco de uma execução
         * @description Devolve o operando, o valor observado, o resultado e a justificativa de cada critério da decisão de risco já tomada para a execução, sem recalcular nada.
         */
        get: operations["consultar_avaliacao_risco_api_v1_execucoes__execucao_id__avaliacao_risco_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar todas as versões de regra
         * @description Devolve todas as versões de regra registradas, ativas e substituídas.
         */
        get: operations["consultar_regras_api_v1_regras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regras/{regra_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar uma versão específica de regra
         * @description Devolve uma versão específica de regra pelo seu identificador.
         */
        get: operations["consultar_regra_api_v1_regras__regra_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regras/{regra_id}/testar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Testar deterministicamente uma configuração de regra
         * @description Aplica a configuração proposta a cada cenário sintético do tipo de evento, sem persistir nada. Configuração inválida é bloqueada com motivos por campo.
         */
        post: operations["testar_regra_api_v1_regras__regra_id__testar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regras/{regra_id}/ativar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ativar uma nova versão de regra
         * @description Revalida e reexecuta o teste determinístico, e ativa a configuração como nova versão da regra informada, de forma idempotente. Exige o cabeçalho `Idempotency-Key` em toda requisição.
         */
        post: operations["ativar_regra_api_v1_regras__regra_id__ativar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/execucoes/{execucao_id}/elegibilidade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar o público elegível de uma execução
         * @description Devolve as quantidades de incluídos e excluídos e a lista do público avaliado, com segurado sintético, apólice, localização, canal e resultado. Uma execução sem nenhum resultado devolve quantidades zeradas e lista vazia.
         */
        get: operations["consultar_elegibilidade_api_v1_execucoes__execucao_id__elegibilidade_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/execucoes/{execucao_id}/elegibilidade/{registro_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar a explicação completa de um resultado de elegibilidade
         * @description Devolve regra e versão, operando, valor observado, resultado e justificativa de cada critério da decisão de elegibilidade já tomada, sem recalcular nada.
         */
        get: operations["consultar_registro_elegibilidade_api_v1_execucoes__execucao_id__elegibilidade__registro_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/execucoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar uma execução preventiva
         * @description Inicia, de forma idempotente, a orquestração completa de coleta, avaliação de risco e avaliação de elegibilidade para a área informada, sem exigir nenhum clique manual intermediário (RUNNER-01). Exige o cabeçalho `Idempotency-Key` em toda requisição.
         */
        post: operations["iniciar_execucao_api_v1_execucoes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/execucoes/{execucao_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar o acompanhamento de uma execução preventiva
         * @description Devolve o estado atual, os marcos de transição já persistidos e, quando o estado é 'aguardando_geracao', a quantidade total e uma prévia do público elegível formado (RUNNER-05). Traz também a navegação entre execuções correlacionadas: a origem desta execução e as novas tentativas criadas a partir dela, sem mesclar históricos.
         */
        get: operations["consultar_execucao_api_v1_execucoes__execucao_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/execucoes/{execucao_id}/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preparar a etapa agêntica de uma execução preventiva
         * @description Verifica a configuração e a disponibilidade real da OpenAI antes de gerar qualquer mensagem e, confirmada a disponibilidade, monta o contexto mínimo de cada item do público elegível e transiciona a execução para 'processando_mensagens'. Indisponibilidade que esgota as tentativas leva a 'falhou_preparacao_ia' com causa sanitizada, sem nenhuma chamada de geração e sem nenhum conteúdo substituto. Exige o cabeçalho `Idempotency-Key`.
         */
        post: operations["preparar_execucao_api_v1_execucoes__execucao_id__preflight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/execucoes/{execucao_origem_id}/nova-tentativa-ia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solicitar nova tentativa de preparação agêntica
         * @description Valida a integridade dos snapshots versionados da execução de origem e, passando, cria uma execução correlacionada nova em 'aguardando_geracao', com `execucao_origem_id` próprio e uma cópia integral do público elegível da origem. A execução de origem permanece terminal e nunca é reaberta. Exige o cabeçalho `Idempotency-Key`.
         */
        post: operations["solicitar_nova_tentativa_ia_api_v1_execucoes__execucao_origem_id__nova_tentativa_ia_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/execucoes/{execucao_id}/contextos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar a proveniência dos contextos preparados
         * @description Devolve, para cada item do público elegível já preparado, quais categorias de dado foram usadas no contexto do agente redator e quais foram deliberadamente deixadas de fora. São nomes de categoria, nunca conteúdo: a consulta nunca expõe documento, dado financeiro, dado de pagamento ou credencial.
         */
        get: operations["consultar_proveniencia_api_v1_execucoes__execucao_id__contextos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErroCampo
         * @description Um erro de validação localizado a um campo específico.
         */
        ErroCampo: {
            /**
             * Campo
             * @description Nome do campo com erro.
             */
            campo: string;
            /**
             * Motivo
             * @description Motivo do erro em português brasileiro.
             */
            motivo: string;
        };
        /**
         * ProblemaAvaliacaoRisco
         * @description Falha da consulta de avaliação de risco, com ocorrência, impacto e próxima ação segura.
         */
        ProblemaAvaliacaoRisco: {
            /**
             * Codigo
             * @description Código estável que identifica o tipo da falha.
             */
            codigo: string;
            /**
             * Correlacao Id
             * @description Identificador único desta ocorrência de falha.
             */
            correlacao_id: string;
            /**
             * Ocorrencia
             * @description O que aconteceu, em português brasileiro.
             */
            ocorrencia: string;
            /**
             * Impacto
             * @description Efeito prático da falha para quem consultou o recurso.
             */
            impacto: string;
            /**
             * Proxima Acao
             * @description Próxima ação segura recomendada para contornar a falha.
             */
            proxima_acao: string;
        };
        /**
         * ProblemaContexto
         * @description Falha da consulta do segurado padrão, com ocorrência, impacto e próxima ação segura.
         */
        ProblemaContexto: {
            /**
             * Codigo
             * @description Código estável que identifica o tipo da falha.
             */
            codigo: string;
            /**
             * Correlacao Id
             * @description Identificador único desta ocorrência de falha.
             */
            correlacao_id: string;
            /**
             * Ocorrencia
             * @description O que aconteceu, em português brasileiro.
             */
            ocorrencia: string;
            /**
             * Impacto
             * @description Efeito prático da falha para quem consultou o recurso.
             */
            impacto: string;
            /**
             * Proxima Acao
             * @description Próxima ação segura recomendada para contornar a falha.
             */
            proxima_acao: string;
        };
        /**
         * ProblemaElegibilidade
         * @description Falha da consulta de elegibilidade, com ocorrência, impacto e próxima ação segura.
         */
        ProblemaElegibilidade: {
            /**
             * Codigo
             * @description Código estável que identifica o tipo da falha.
             */
            codigo: string;
            /**
             * Correlacao Id
             * @description Identificador único desta ocorrência de falha.
             */
            correlacao_id: string;
            /**
             * Ocorrencia
             * @description O que aconteceu, em português brasileiro.
             */
            ocorrencia: string;
            /**
             * Impacto
             * @description Efeito prático da falha para quem consultou o recurso.
             */
            impacto: string;
            /**
             * Proxima Acao
             * @description Próxima ação segura recomendada para contornar a falha.
             */
            proxima_acao: string;
        };
        /**
         * ProblemaExecucao
         * @description Falha da operação de execução, com ocorrência, impacto e próxima ação segura.
         */
        ProblemaExecucao: {
            /**
             * Codigo
             * @description Código estável que identifica o tipo da falha.
             */
            codigo: string;
            /**
             * Correlacao Id
             * @description Identificador único desta ocorrência de falha.
             */
            correlacao_id: string;
            /**
             * Ocorrencia
             * @description O que aconteceu, em português brasileiro.
             */
            ocorrencia: string;
            /**
             * Impacto
             * @description Efeito prático da falha para quem consultou o recurso.
             */
            impacto: string;
            /**
             * Proxima Acao
             * @description Próxima ação segura recomendada para contornar a falha.
             */
            proxima_acao: string;
        };
        /**
         * ProblemaMeteorologia
         * @description Falha de uma operação meteorológica, com ocorrência, impacto e próxima ação segura.
         */
        ProblemaMeteorologia: {
            /**
             * Codigo
             * @description Código estável que identifica o tipo da falha.
             */
            codigo: string;
            /**
             * Correlacao Id
             * @description Identificador único desta ocorrência de falha.
             */
            correlacao_id: string;
            /**
             * Ocorrencia
             * @description O que aconteceu, em português brasileiro.
             */
            ocorrencia: string;
            /**
             * Impacto
             * @description Efeito prático da falha para quem consultou o recurso.
             */
            impacto: string;
            /**
             * Proxima Acao
             * @description Próxima ação segura recomendada para contornar a falha.
             */
            proxima_acao: string;
        };
        /**
         * ProblemaPreflight
         * @description Falha da preparação agêntica, com ocorrência, impacto e próxima ação segura.
         */
        ProblemaPreflight: {
            /**
             * Codigo
             * @description Código estável que identifica o tipo da falha.
             */
            codigo: string;
            /**
             * Correlacao Id
             * @description Identificador único desta ocorrência de falha.
             */
            correlacao_id: string;
            /**
             * Ocorrencia
             * @description O que aconteceu, em português brasileiro.
             */
            ocorrencia: string;
            /**
             * Impacto
             * @description Efeito prático da falha para quem solicitou a operação.
             */
            impacto: string;
            /**
             * Proxima Acao
             * @description Próxima ação segura recomendada para contornar a falha.
             */
            proxima_acao: string;
        };
        /**
         * ProblemaProntidao
         * @description Falha da operação de prontidão, com ocorrência, impacto e próxima ação segura.
         */
        ProblemaProntidao: {
            /**
             * Codigo
             * @description Código estável que identifica o tipo da falha.
             */
            codigo: string;
            /**
             * Correlacao Id
             * @description Identificador único desta ocorrência de falha.
             */
            correlacao_id: string;
            /**
             * Ocorrencia
             * @description O que aconteceu, em português brasileiro.
             */
            ocorrencia: string;
            /**
             * Impacto
             * @description Efeito prático da falha para quem consultou o recurso.
             */
            impacto: string;
            /**
             * Proxima Acao
             * @description Próxima ação segura recomendada para contornar a falha.
             */
            proxima_acao: string;
        };
        /**
         * ProblemaRegras
         * @description Falha de uma operação de regras, com ocorrência, impacto e próxima ação segura.
         */
        ProblemaRegras: {
            /**
             * Codigo
             * @description Código estável que identifica o tipo da falha.
             */
            codigo: string;
            /**
             * Correlacao Id
             * @description Identificador único desta ocorrência de falha.
             */
            correlacao_id: string;
            /**
             * Ocorrencia
             * @description O que aconteceu, em português brasileiro.
             */
            ocorrencia: string;
            /**
             * Impacto
             * @description Efeito prático da falha para quem consultou o recurso.
             */
            impacto: string;
            /**
             * Proxima Acao
             * @description Próxima ação segura recomendada para contornar a falha.
             */
            proxima_acao: string;
            /**
             * Erros
             * @description Erros por campo, quando a falha vem de uma configuração inválida.
             */
            erros?: components["schemas"]["ErroCampo"][];
        };
        /**
         * ProblemaRestauracao
         * @description Falha da restauração, com ocorrência, impacto e próxima ação segura.
         */
        ProblemaRestauracao: {
            /**
             * Codigo
             * @description Código estável que identifica o tipo da falha.
             */
            codigo: string;
            /**
             * Correlacao Id
             * @description Identificador único desta ocorrência de falha.
             */
            correlacao_id: string;
            /**
             * Ocorrencia
             * @description O que aconteceu, em português brasileiro.
             */
            ocorrencia: string;
            /**
             * Impacto
             * @description Efeito prático da falha para quem consultou o recurso.
             */
            impacto: string;
            /**
             * Proxima Acao
             * @description Próxima ação segura recomendada para contornar a falha.
             */
            proxima_acao: string;
        };
        /**
         * RespostaAvaliacaoRisco
         * @description Snapshot público da avaliação de relevância meteorológica de uma execução.
         */
        RespostaAvaliacaoRisco: {
            /**
             * Execucao Id
             * Format: uuid
             * @description Identificador da execução avaliada.
             */
            execucao_id: string;
            /**
             * Evento Id
             * Format: uuid
             * @description Identificador do evento meteorológico avaliado.
             */
            evento_id: string;
            /**
             * Regra Id
             * @description Identificador da regra aplicada, ou nulo se não havia regra ativa.
             */
            regra_id: string | null;
            /**
             * Regra Versao
             * @description Versão da regra no momento da avaliação, ou nulo se não havia regra ativa.
             */
            regra_versao: number | null;
            /**
             * Relevante
             * @description Se o evento foi considerado relevante.
             */
            relevante: boolean;
            /**
             * Criterios
             * @description Critérios avaliados, na ordem aplicada.
             */
            criterios: components["schemas"]["RespostaCriterio"][];
            /**
             * Motivo
             * @description Motivo tipado do resultado.
             */
            motivo: string;
            /**
             * Criado Em
             * Format: date-time
             * @description Instante RFC 3339 em UTC da avaliação.
             */
            criado_em: string;
        };
        /**
         * RespostaCasoTeste
         * @description Um caso de teste determinístico: o cenário sintético usado e o resultado obtido.
         */
        RespostaCasoTeste: {
            /**
             * Evento Id
             * Format: uuid
             * @description Identificador do evento sintético usado no teste.
             */
            evento_id: string;
            /**
             * Relevante
             * @description Se o cenário foi considerado relevante pela regra.
             */
            relevante: boolean;
            /**
             * Criterios
             * @description Critérios avaliados neste caso.
             */
            criterios: components["schemas"]["RespostaCriterioTeste"][];
            /**
             * Motivo
             * @description Motivo tipado do resultado deste caso.
             */
            motivo: string;
        };
        /**
         * RespostaColetaAceita
         * @description Ack público de uma solicitação de coleta manual aceita ou já registrada.
         */
        RespostaColetaAceita: {
            /**
             * Id
             * Format: uuid
             * @description Identificador da sincronização criada ou já registrada.
             */
            id: string;
            /**
             * Requisicao Id
             * Format: uuid
             * @description Identificador de correlação da tentativa.
             */
            requisicao_id: string;
            /**
             * Estado
             * @description Estado da sincronização no momento da resposta.
             */
            estado: string;
            /**
             * Registros Validos
             * @description Quantidade de eventos válidos produzidos.
             */
            registros_validos: number;
            /**
             * Motivo Falha
             * @description Motivo tipado da falha, ou nulo se não houve.
             */
            motivo_falha: string | null;
            /**
             * Aceito Em
             * Format: date-time
             * @description Instante RFC 3339 em UTC em que a solicitação foi aceita.
             */
            aceito_em: string;
        };
        /**
         * RespostaCriterio
         * @description Um critério avaliado: operando, valor observado, resultado e justificativa.
         */
        RespostaCriterio: {
            /**
             * Operando
             * @description O que foi comparado (ex.: área aplicável, intensidade).
             */
            operando: string;
            /**
             * Valor Observado
             * @description Valor observado no evento para este critério.
             */
            valor_observado: string;
            /**
             * Atende
             * @description Se o valor observado atende ao critério.
             */
            atende: boolean;
            /**
             * Justificativa
             * @description Explicação em português brasileiro do resultado.
             */
            justificativa: string;
        };
        /**
         * RespostaCriterioElegibilidade
         * @description Um critério avaliado: operando, valor observado, resultado e justificativa.
         */
        RespostaCriterioElegibilidade: {
            /**
             * Operando
             * @description O que foi comparado (ex.: área afetada, cobertura).
             */
            operando: string;
            /**
             * Valor Observado
             * @description Valor observado para este critério.
             */
            valor_observado: string;
            /**
             * Atende
             * @description Se o valor observado atende ao critério.
             */
            atende: boolean;
            /**
             * Justificativa
             * @description Explicação em português brasileiro do resultado.
             */
            justificativa: string;
        };
        /**
         * RespostaCriterioTeste
         * @description Um critério avaliado no teste determinístico: operando, valor, resultado e justificativa.
         */
        RespostaCriterioTeste: {
            /**
             * Operando
             * @description O que foi comparado (ex.: área aplicável, intensidade).
             */
            operando: string;
            /**
             * Valor Observado
             * @description Valor observado no evento para este critério.
             */
            valor_observado: string;
            /**
             * Atende
             * @description Se o valor observado atende ao critério.
             */
            atende: boolean;
            /**
             * Justificativa
             * @description Explicação em português brasileiro do resultado.
             */
            justificativa: string;
        };
        /**
         * RespostaDependencia
         * @description Estado de prontidão de uma única dependência, pronto para exibição.
         */
        RespostaDependencia: {
            /**
             * Nome
             * @description Nome canônico da dependência verificada.
             */
            nome: string;
            /**
             * Estado
             * @description Estado atual de prontidão da dependência.
             */
            estado: string;
            /**
             * Verificado Em
             * @description Instante RFC 3339 em UTC da última verificação, ou nulo se ainda não houve.
             */
            verificado_em: string | null;
            /**
             * Causa
             * @description Causa da indisponibilidade ou degradação, ou nula quando disponível.
             */
            causa: string | null;
            /**
             * Impacto
             * @description Efeito prático do estado atual para quem consulta.
             */
            impacto: string;
            /**
             * Acao Disponivel
             * @description Ação segura disponível dado o estado atual.
             */
            acao_disponivel: string;
        };
        /**
         * RespostaDependencias
         * @description Resposta pública consolidada das 4 dependências.
         */
        RespostaDependencias: {
            /**
             * Dependencias
             * @description Estado de prontidão de cada uma das 4 dependências monitoradas.
             */
            dependencias: components["schemas"]["RespostaDependencia"][];
        };
        /**
         * RespostaDetalheElegibilidade
         * @description Explicação completa de um resultado de elegibilidade (ELEG-09).
         */
        RespostaDetalheElegibilidade: {
            /**
             * Id
             * Format: uuid
             * @description Identificador do resultado de elegibilidade.
             */
            id: string;
            /**
             * Execucao Id
             * Format: uuid
             * @description Identificador da execução avaliada.
             */
            execucao_id: string;
            /**
             * Evento Id
             * Format: uuid
             * @description Identificador do evento meteorológico avaliado.
             */
            evento_id: string;
            /**
             * Regra Id
             * Format: uuid
             * @description Identificador da versão de regra usada na avaliação.
             */
            regra_id: string;
            /**
             * Regra Versao
             * @description Versão da regra usada na avaliação.
             */
            regra_versao: number;
            /**
             * Segurado Id
             * Format: uuid
             * @description Identificador do segurado avaliado.
             */
            segurado_id: string;
            /**
             * Nome Segurado
             * @description Nome do segurado sintético avaliado.
             */
            nome_segurado: string;
            /**
             * Apolice Id
             * Format: uuid
             * @description Identificador da apólice avaliada.
             */
            apolice_id: string;
            /**
             * Codigo Ibge Area
             * @description Código IBGE da área da apólice avaliada.
             */
            codigo_ibge_area: string;
            /**
             * Elegivel
             * @description Se a combinação foi incluída no público elegível.
             */
            elegivel: boolean;
            /**
             * Criterios
             * @description Critérios avaliados, na ordem aplicada.
             */
            criterios: components["schemas"]["RespostaCriterioElegibilidade"][];
            /**
             * Canal
             * @description Canal preferencial do segurado, no momento da avaliação.
             */
            canal: string;
            /**
             * Justificativa
             * @description Explicação objetiva do resultado, em português.
             */
            justificativa: string;
            /**
             * Criado Em
             * Format: date-time
             * @description Instante RFC 3339 em UTC da avaliação.
             */
            criado_em: string;
        };
        /**
         * RespostaElegibilidade
         * @description Quantidades e lista do público avaliado de uma execução (ELEG-08).
         */
        RespostaElegibilidade: {
            /**
             * Incluidos
             * @description Quantidade de resultados incluídos.
             */
            incluidos: number;
            /**
             * Excluidos
             * @description Quantidade de resultados excluídos.
             */
            excluidos: number;
            /**
             * Registros
             * @description Resultados de elegibilidade, mais recentes primeiro.
             */
            registros: components["schemas"]["RespostaResumoElegibilidade"][];
        };
        /**
         * RespostaEvento
         * @description Evento meteorológico normalizado, pronto para exibição.
         */
        RespostaEvento: {
            /**
             * Id
             * Format: uuid
             * @description Identificador do evento meteorológico.
             */
            id: string;
            /**
             * Tipo
             * @description Tipo do evento (`chuva_intensa` ou `granizo`).
             */
            tipo: string;
            /**
             * Area
             * @description Código IBGE da área onde o evento foi observado.
             */
            area: string;
            /**
             * Periodo Inicio
             * Format: date-time
             * @description Início RFC 3339 em UTC do período do evento.
             */
            periodo_inicio: string;
            /**
             * Periodo Fim
             * Format: date-time
             * @description Término RFC 3339 em UTC do período do evento.
             */
            periodo_fim: string;
            /**
             * Intensidade
             * @description Intensidade normalizada da medida observada.
             */
            intensidade: number;
            /**
             * Proveniencia
             * @description Origem do evento (`real_inmet` ou `sintetico`).
             */
            proveniencia: string;
            /**
             * Instante Observado
             * Format: date-time
             * @description Instante RFC 3339 em UTC em que a medida foi observada.
             */
            instante_observado: string;
        };
        /**
         * RespostaEventos
         * @description Lista pública de eventos meteorológicos normalizados.
         */
        RespostaEventos: {
            /**
             * Eventos
             * @description Eventos meteorológicos, do mais recente.
             */
            eventos: components["schemas"]["RespostaEvento"][];
        };
        /**
         * RespostaExecucao
         * @description Estado, marcos e, quando aplicável, prévia do público elegível de uma execução.
         */
        RespostaExecucao: {
            /**
             * Id
             * Format: uuid
             * @description Identificador da execução.
             */
            id: string;
            /**
             * Estado
             * @description Estado atual da execução.
             */
            estado: string;
            /**
             * Marcos
             * @description Marcos de transição já persistidos, na ordem em que ocorreram.
             */
            marcos: components["schemas"]["RespostaMarco"][];
            /**
             * Publico Elegivel Total
             * @description Quantidade total de incluídos no público elegível; nulo fora de 'aguardando_geracao'.
             */
            publico_elegivel_total: number | null;
            /**
             * Publico Elegivel Previa
             * @description Amostra de até 5 incluídos no público elegível; vazia fora de 'aguardando_geracao'.
             */
            publico_elegivel_previa: components["schemas"]["RespostaPreviaPublico"][];
            /**
             * Execucao Origem Id
             * @description Execução terminal que originou esta nova tentativa; nula quando esta execução não é correlacionada a nenhuma outra.
             */
            execucao_origem_id: string | null;
            /**
             * Retentativas
             * @description Execuções criadas como nova tentativa a partir desta; vazia quando não houve nenhuma. Cada execução mantém seu próprio histórico, sem mesclar marcos.
             */
            retentativas: string[];
        };
        /**
         * RespostaExecucaoAceita
         * @description Ack público de uma execução criada ou já em andamento com a mesma chave.
         */
        RespostaExecucaoAceita: {
            /**
             * Execucao Id
             * Format: uuid
             * @description Identificador da execução criada ou já em andamento.
             */
            execucao_id: string;
        };
        /**
         * RespostaHistoricoSincronizacoes
         * @description Histórico de sincronização, com os marcos exigidos pela consulta de Marina.
         */
        RespostaHistoricoSincronizacoes: {
            /** @description Tentativa mais recente registrada, ou nula se nunca houve nenhuma. */
            ultima_tentativa: components["schemas"]["RespostaSincronizacao"] | null;
            /** @description Última tentativa concluída com sucesso, ou nula se nenhuma concluiu. */
            ultima_valida: components["schemas"]["RespostaSincronizacao"] | null;
            /**
             * Proxima Consulta
             * @description Instante RFC 3339 em UTC estimado da próxima coleta automática.
             */
            proxima_consulta: string | null;
            /**
             * Resultados Anteriores
             * @description Histórico completo, da tentativa mais recente para a mais antiga.
             */
            resultados_anteriores: components["schemas"]["RespostaSincronizacao"][];
        };
        /**
         * RespostaMarco
         * @description Um marco de transição já persistido da execução.
         */
        RespostaMarco: {
            /**
             * Marco
             * @description Nome do marco de transição.
             */
            marco: string;
            /**
             * Causa
             * @description Causa registrada, ou nula quando não houve falha.
             */
            causa: string | null;
            /**
             * Criado Em
             * Format: date-time
             * @description Instante RFC 3339 em UTC em que o marco foi registrado.
             */
            criado_em: string;
        };
        /**
         * RespostaNovaTentativaIA
         * @description Ack da execução correlacionada criada a partir de uma falha de preparação.
         */
        RespostaNovaTentativaIA: {
            /**
             * Execucao Id
             * Format: uuid
             * @description Identificador da execução correlacionada criada.
             */
            execucao_id: string;
            /**
             * Execucao Origem Id
             * Format: uuid
             * @description Identificador da execução terminal que originou a nova tentativa.
             */
            execucao_origem_id: string;
        };
        /**
         * RespostaPreflight
         * @description Desfecho do preflight de uma execução: estado alcançado e o que foi preparado.
         */
        RespostaPreflight: {
            /**
             * Execucao Id
             * Format: uuid
             * @description Identificador da execução preparada.
             */
            execucao_id: string;
            /**
             * Estado
             * @description Estado alcançado pela execução após o preflight.
             */
            estado: string;
            /**
             * Contextos Montados
             * @description Quantidade de itens do público elegível com contexto mínimo montado.
             */
            contextos_montados: number;
            /**
             * Itens Em Excecao
             * @description Itens cujo contexto não pôde ser montado; os demais seguem normalmente.
             */
            itens_em_excecao: string[];
            /**
             * Causa
             * @description Causa sanitizada do bloqueio, ou nula quando o preflight foi bem-sucedido.
             */
            causa: string | null;
        };
        /**
         * RespostaPreviaPublico
         * @description Um item da amostra do público elegível formado.
         */
        RespostaPreviaPublico: {
            /**
             * Nome Segurado
             * @description Nome do segurado sintético incluído.
             */
            nome_segurado: string;
            /**
             * Canal
             * @description Canal preferencial do segurado, no momento da avaliação.
             */
            canal: string;
        };
        /**
         * RespostaProvenienciaContexto
         * @description Proveniência do contexto minimizado de um item: o que foi e o que não foi usado.
         */
        RespostaProvenienciaContexto: {
            /**
             * Elegibilidade Id
             * Format: uuid
             * @description Item do público elegível preparado.
             */
            elegibilidade_id: string;
            /**
             * Categorias Usadas
             * @description Categorias de dado que chegaram ao contexto do agente redator.
             */
            categorias_usadas: string[];
            /**
             * Categorias Nao Usadas
             * @description Categorias deliberadamente deixadas de fora do contexto.
             */
            categorias_nao_usadas: string[];
        };
        /**
         * RespostaProveniencias
         * @description Proveniência dos contextos já montados de uma execução (PREFL-14).
         */
        RespostaProveniencias: {
            /**
             * Registros
             * @description Proveniência de cada item preparado, na ordem em que foi montado.
             */
            registros: components["schemas"]["RespostaProvenienciaContexto"][];
        };
        /**
         * RespostaRegra
         * @description Uma versão de regra, para consulta e auditoria.
         */
        RespostaRegra: {
            /**
             * Id
             * Format: uuid
             * @description Identificador desta versão de regra.
             */
            id: string;
            /**
             * Evento Tipo
             * @description Tipo de evento (`chuva_intensa` ou `granizo`).
             */
            evento_tipo: string;
            /**
             * Limiar Meteorologico
             * @description Limiar numérico usado pela regra.
             */
            limiar_meteorologico: number;
            /**
             * Area Aplicavel
             * @description Código IBGE da área a que a regra se aplica.
             */
            area_aplicavel: string;
            /**
             * Apolice Tipo
             * @description Tipo de apólice (`residencial` ou `automovel`).
             */
            apolice_tipo: string;
            /**
             * Cobertura Exigida
             * @description Cobertura que a apólice precisa ter.
             */
            cobertura_exigida: string;
            /**
             * Antecedencia Horas
             * @description Antecedência do alerta preventivo, em horas.
             */
            antecedencia_horas: number;
            /**
             * Canal
             * @description Canal de comunicação (`whatsapp`, `email` ou `sms`).
             */
            canal: string;
            /**
             * Versao
             * @description Número sequencial desta versão da regra.
             */
            versao: number;
            /**
             * Estado
             * @description Estado da versão (`ativa` ou `substituida`).
             */
            estado: string;
        };
        /**
         * RespostaRegras
         * @description Lista pública de versões de regra.
         */
        RespostaRegras: {
            /**
             * Regras
             * @description Versões de regra, mais recentes primeiro.
             */
            regras: components["schemas"]["RespostaRegra"][];
        };
        /**
         * RespostaRestauracao
         * @description Resposta pública de uma restauração concluída.
         */
        RespostaRestauracao: {
            /**
             * Status
             * @description Resultado da restauração concluída.
             * @constant
             */
            status: "restaurado";
            /**
             * Restaurado Em
             * Format: date-time
             * @description Instante RFC 3339 em UTC em que a restauração foi concluída.
             */
            restaurado_em: string;
        };
        /**
         * RespostaResumoElegibilidade
         * @description Um resultado de elegibilidade na listagem: segurado, apólice, localização, canal.
         */
        RespostaResumoElegibilidade: {
            /**
             * Id
             * Format: uuid
             * @description Identificador do resultado de elegibilidade.
             */
            id: string;
            /**
             * Nome Segurado
             * @description Nome do segurado sintético avaliado.
             */
            nome_segurado: string;
            /**
             * Apolice Id
             * Format: uuid
             * @description Identificador da apólice avaliada.
             */
            apolice_id: string;
            /**
             * Codigo Ibge Area
             * @description Código IBGE da área da apólice avaliada.
             */
            codigo_ibge_area: string;
            /**
             * Canal
             * @description Canal preferencial do segurado, no momento da avaliação.
             */
            canal: string;
            /**
             * Elegivel
             * @description Se a combinação foi incluída no público elegível.
             */
            elegivel: boolean;
        };
        /**
         * RespostaSaude
         * @description Resposta pública da disponibilidade do processo backend.
         */
        RespostaSaude: {
            /**
             * Status
             * @description Disponibilidade do processo backend.
             * @constant
             */
            status: "disponivel";
            /**
             * Ambiente
             * @description Ambiente de execução do processo.
             * @constant
             */
            ambiente: "educacional";
        };
        /**
         * RespostaSeguradoPadrao
         * @description Resposta pública do segurado sintético padrão.
         */
        RespostaSeguradoPadrao: {
            /**
             * Id
             * @description Identificador opaco do segurado sintético padrão.
             */
            id: string;
            /**
             * Nome
             * @description Nome do segurado sintético padrão.
             */
            nome: string;
        };
        /**
         * RespostaSincronizacao
         * @description Registro público de uma tentativa de sincronização meteorológica.
         */
        RespostaSincronizacao: {
            /**
             * Id
             * Format: uuid
             * @description Identificador da sincronização.
             */
            id: string;
            /**
             * Requisicao Id
             * Format: uuid
             * @description Identificador de correlação da tentativa.
             */
            requisicao_id: string;
            /**
             * Area Monitorada Id
             * Format: uuid
             * @description Identificador da área monitorada desta sincronização.
             */
            area_monitorada_id: string;
            /**
             * Origem
             * @description Origem da tentativa (`automatica` ou `manual`).
             */
            origem: string;
            /**
             * Estado
             * @description Estado atual da sincronização.
             */
            estado: string;
            /**
             * Registros Validos
             * @description Quantidade de eventos válidos produzidos.
             */
            registros_validos: number;
            /**
             * Motivo Falha
             * @description Motivo tipado da falha, ou nulo se não houve.
             */
            motivo_falha: string | null;
            /**
             * Iniciado Em
             * Format: date-time
             * @description Instante RFC 3339 em UTC de início da tentativa.
             */
            iniciado_em: string;
            /**
             * Finalizado Em
             * @description Instante RFC 3339 em UTC de término, ou nulo se em andamento.
             */
            finalizado_em: string | null;
            /**
             * Tentativas
             * @description Tentativas individuais desta sincronização, em ordem crescente de número.
             */
            tentativas: components["schemas"]["RespostaTentativa"][];
            /**
             * Limite Tentativas
             * @description Número máximo de tentativas totais de uma coleta (RESIL-01).
             */
            limite_tentativas: number;
        };
        /**
         * RespostaTentativa
         * @description Tentativa individual de coleta dentro de uma sincronização com retry (RESIL-02).
         */
        RespostaTentativa: {
            /**
             * Numero Tentativa
             * @description Número sequencial da tentativa (1 a 3).
             */
            numero_tentativa: number;
            /**
             * Codigo Resultado
             * @description Resultado da tentativa (`sucesso`, `timeout`, `erro_transporte`, `status_erro`).
             */
            codigo_resultado: string;
            /**
             * Iniciado Em
             * Format: date-time
             * @description Instante RFC 3339 em UTC de início da tentativa.
             */
            iniciado_em: string;
            /**
             * Finalizado Em
             * Format: date-time
             * @description Instante RFC 3339 em UTC de término da tentativa.
             */
            finalizado_em: string;
        };
        /**
         * RespostaTeste
         * @description Resultado do teste determinístico, um caso por cenário sintético aplicável.
         */
        RespostaTeste: {
            /**
             * Casos
             * @description Casos de teste, um por cenário sintético do tipo de evento da regra.
             */
            casos: components["schemas"]["RespostaCasoTeste"][];
        };
        /**
         * RespostaVerificacaoAceita
         * @description Ack de uma nova verificação aceita para processamento em segundo plano.
         */
        RespostaVerificacaoAceita: {
            /**
             * Nome
             * @description Nome canônico da dependência cuja verificação foi aceita.
             */
            nome: string;
            /**
             * Estado
             * @description Estado da dependência no momento em que a verificação foi aceita.
             */
            estado: string;
            /**
             * Aceito Em
             * Format: date-time
             * @description Instante RFC 3339 em UTC em que a nova verificação foi aceita.
             */
            aceito_em: string;
        };
        /**
         * SolicitacaoAtivarCenarioSintetico
         * @description Corpo da ativação de um cenário sintético: a área monitorada a usar.
         */
        SolicitacaoAtivarCenarioSintetico: {
            /**
             * Area Id
             * Format: uuid
             * @description Identificador da área monitorada onde ativar o cenário.
             */
            area_id: string;
        };
        /**
         * SolicitacaoAtivarRegra
         * @description Configuração de regra proposta, mais a versão esperada para concorrência otimista.
         */
        SolicitacaoAtivarRegra: {
            /**
             * Evento Tipo
             * @description Tipo de evento (`chuva_intensa` ou `granizo`).
             */
            evento_tipo: string;
            /**
             * Limiar Meteorologico
             * @description Limiar numérico usado pela regra.
             */
            limiar_meteorologico: number;
            /**
             * Area Aplicavel
             * @description Código IBGE da área a que a regra se aplica.
             */
            area_aplicavel: string;
            /**
             * Apolice Tipo
             * @description Tipo de apólice (`residencial` ou `automovel`).
             */
            apolice_tipo: string;
            /**
             * Cobertura Exigida
             * @description Cobertura que a apólice precisa ter.
             */
            cobertura_exigida: string;
            /**
             * Antecedencia Horas
             * @description Antecedência do alerta preventivo, em horas.
             */
            antecedencia_horas: number;
            /**
             * Canal
             * @description Canal de comunicação (`whatsapp`, `email` ou `sms`).
             */
            canal: string;
            /**
             * Versao Esperada
             * @description Versão ativa esperada da regra anterior (concorrência otimista, AD-008).
             */
            versao_esperada: number;
        };
        /**
         * SolicitacaoColeta
         * @description Corpo da solicitação de coleta manual: a área monitorada a consultar.
         */
        SolicitacaoColeta: {
            /**
             * Area Id
             * Format: uuid
             * @description Identificador da área monitorada a coletar.
             */
            area_id: string;
        };
        /**
         * SolicitacaoExecucao
         * @description Corpo da solicitação de início de execução: a área monitorada a avaliar.
         */
        SolicitacaoExecucao: {
            /**
             * Area Id
             * Format: uuid
             * @description Identificador da área monitorada a avaliar.
             */
            area_id: string;
        };
        /**
         * SolicitacaoRegra
         * @description Configuração de regra proposta, no formato aceito por `testar`/`ativar`.
         */
        SolicitacaoRegra: {
            /**
             * Evento Tipo
             * @description Tipo de evento (`chuva_intensa` ou `granizo`).
             */
            evento_tipo: string;
            /**
             * Limiar Meteorologico
             * @description Limiar numérico usado pela regra.
             */
            limiar_meteorologico: number;
            /**
             * Area Aplicavel
             * @description Código IBGE da área a que a regra se aplica.
             */
            area_aplicavel: string;
            /**
             * Apolice Tipo
             * @description Tipo de apólice (`residencial` ou `automovel`).
             */
            apolice_tipo: string;
            /**
             * Cobertura Exigida
             * @description Cobertura que a apólice precisa ter.
             */
            cobertura_exigida: string;
            /**
             * Antecedencia Horas
             * @description Antecedência do alerta preventivo, em horas.
             */
            antecedencia_horas: number;
            /**
             * Canal
             * @description Canal de comunicação (`whatsapp`, `email` ou `sms`).
             */
            canal: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    obter_saude_api_v1_saude_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saúde do processo confirmada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaSaude"];
                };
            };
        };
    };
    restaurar_api_v1_dados_sinteticos_restauracoes_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados sintéticos restaurados. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaRestauracao"];
                };
            };
            /** @description Restauração recusada sem qualquer mutação. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRestauracao"];
                };
            };
            /** @description Requisição sem o cabeçalho `Idempotency-Key`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRestauracao"];
                };
            };
            /** @description Falha ao concluir a transação de restauração. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRestauracao"];
                };
            };
        };
    };
    consultar_api_v1_prontidao_dependencias_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado de prontidão das 4 dependências. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDependencias"];
                };
            };
        };
    };
    verificar_novamente_api_v1_prontidao_dependencias__nome__verificacoes_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                nome: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nova verificação aceita e em andamento. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaVerificacaoAceita"];
                };
            };
            /** @description Dependência desconhecida. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaProntidao"];
                };
            };
            /** @description Conflito de idempotência ou verificação já em andamento. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaProntidao"];
                };
            };
            /** @description Cabeçalho ausente ou dependência local sem re-verificação. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaProntidao"];
                };
            };
        };
    };
    consultar_api_v1_segurados_padrao_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Segurado sintético padrão encontrado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaSeguradoPadrao"];
                };
            };
            /** @description Dados sintéticos ainda não restaurados. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaContexto"];
                };
            };
        };
    };
    solicitar_coleta_api_v1_meteorologia_coletas_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitacaoColeta"];
            };
        };
        responses: {
            /** @description Coleta manual aceita e concluída. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaColetaAceita"];
                };
            };
            /** @description Área monitorada desconhecida. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
            /** @description Conflito de idempotência. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
            /** @description Requisição sem o cabeçalho `Idempotency-Key`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
        };
    };
    solicitar_nova_tentativa_api_v1_meteorologia__sincronizacao_id__nova_tentativa_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                sincronizacao_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nova tentativa aceita e concluída. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaColetaAceita"];
                };
            };
            /** @description Sincronização de origem ou área monitorada desconhecida. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
            /** @description Conflito de idempotência. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
            /** @description Requisição sem o cabeçalho `Idempotency-Key`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
        };
    };
    ativar_cenario_sintetico_api_v1_meteorologia_cenarios_sinteticos__identificador__ativar_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                identificador: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitacaoAtivarCenarioSintetico"];
            };
        };
        responses: {
            /** @description Cenário sintético ativado. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaColetaAceita"];
                };
            };
            /** @description Área monitorada desconhecida. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
            /** @description Conflito de idempotência. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
            /** @description Requisição sem o cabeçalho `Idempotency-Key`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
        };
    };
    consultar_eventos_api_v1_meteorologia_eventos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eventos meteorológicos normalizados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaEventos"];
                };
            };
        };
    };
    consultar_sincronizacoes_api_v1_meteorologia_sincronizacoes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Histórico de sincronizações meteorológicas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaHistoricoSincronizacoes"];
                };
            };
        };
    };
    consultar_avaliacao_risco_api_v1_execucoes__execucao_id__avaliacao_risco_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execucao_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Avaliação de risco encontrada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaAvaliacaoRisco"];
                };
            };
            /** @description A execução ainda não tem avaliação de risco. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaAvaliacaoRisco"];
                };
            };
            /** @description O identificador da execução não é um UUID válido. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaAvaliacaoRisco"];
                };
            };
        };
    };
    consultar_regras_api_v1_regras_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versões de regra. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaRegras"];
                };
            };
        };
    };
    consultar_regra_api_v1_regras__regra_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                regra_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versão de regra encontrada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaRegra"];
                };
            };
            /** @description Regra não encontrada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRegras"];
                };
            };
            /** @description O identificador da regra não é um UUID válido. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRegras"];
                };
            };
        };
    };
    testar_regra_api_v1_regras__regra_id__testar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                regra_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitacaoRegra"];
            };
        };
        responses: {
            /** @description Resultado do teste determinístico (pode ser vazio). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaTeste"];
                };
            };
            /** @description Identificador inválido ou configuração de regra inválida. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRegras"];
                };
            };
        };
    };
    ativar_regra_api_v1_regras__regra_id__ativar_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                regra_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitacaoAtivarRegra"];
            };
        };
        responses: {
            /** @description Nova versão ativada, ou resposta idempotente repetida. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaRegra"];
                };
            };
            /** @description Regra anterior não encontrada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRegras"];
                };
            };
            /** @description Conflito de versão ou de idempotência. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRegras"];
                };
            };
            /** @description Identificador inválido, configuração inválida, cabeçalho `Idempotency-Key` ausente ou nenhum cenário sintético aplicável. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRegras"];
                };
            };
        };
    };
    consultar_elegibilidade_api_v1_execucoes__execucao_id__elegibilidade_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execucao_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Público elegível encontrado (pode ser vazio). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaElegibilidade"];
                };
            };
            /** @description O identificador da execução não é um UUID válido. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaElegibilidade"];
                };
            };
        };
    };
    consultar_registro_elegibilidade_api_v1_execucoes__execucao_id__elegibilidade__registro_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execucao_id: string;
                registro_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultado de elegibilidade encontrado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDetalheElegibilidade"];
                };
            };
            /** @description Resultado inexistente ou de outra execução. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaElegibilidade"];
                };
            };
            /** @description Algum identificador informado não é um UUID válido. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaElegibilidade"];
                };
            };
        };
    };
    iniciar_execucao_api_v1_execucoes_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitacaoExecucao"];
            };
        };
        responses: {
            /** @description Execução aceita e em andamento. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaExecucaoAceita"];
                };
            };
            /** @description Área monitorada desconhecida. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaExecucao"];
                };
            };
            /** @description Conflito de idempotência. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaExecucao"];
                };
            };
            /** @description Requisição sem o cabeçalho `Idempotency-Key`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaExecucao"];
                };
            };
        };
    };
    consultar_execucao_api_v1_execucoes__execucao_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execucao_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Execução encontrada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaExecucao"];
                };
            };
            /** @description Execução inexistente. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaExecucao"];
                };
            };
            /** @description O identificador da execução não é um UUID válido. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaExecucao"];
                };
            };
        };
    };
    preparar_execucao_api_v1_execucoes__execucao_id__preflight_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                execucao_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preflight concluído; o corpo informa o estado alcançado. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaPreflight"];
                };
            };
            /** @description Execução inexistente. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaPreflight"];
                };
            };
            /** @description Execução fora de 'aguardando_geracao' ou conflito de chave. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaPreflight"];
                };
            };
            /** @description Requisição sem `Idempotency-Key` ou identificador inválido. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaPreflight"];
                };
            };
        };
    };
    solicitar_nova_tentativa_ia_api_v1_execucoes__execucao_origem_id__nova_tentativa_ia_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                execucao_origem_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Execução correlacionada criada. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaNovaTentativaIA"];
                };
            };
            /** @description Execução de origem inexistente. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaPreflight"];
                };
            };
            /** @description Origem fora de 'falhou_preparacao_ia' ou conflito de chave. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaPreflight"];
                };
            };
            /** @description Requisição sem `Idempotency-Key`, identificador inválido ou snapshot da origem incompleto. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaPreflight"];
                };
            };
        };
    };
    consultar_proveniencia_api_v1_execucoes__execucao_id__contextos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execucao_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proveniência encontrada (pode ser vazia). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaProveniencias"];
                };
            };
            /** @description Execução inexistente. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaPreflight"];
                };
            };
            /** @description O identificador da execução não é um UUID válido. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaPreflight"];
                };
            };
        };
    };
}
