/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/dados-sinteticos/restauracoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restaurar os dados sintéticos da demonstração
         * @description Repõe o conjunto sintético versionado em uma única transação. Exige o cabeçalho `Idempotency-Key` em toda requisição.
         */
        post: operations["restaurar_api_v1_dados_sinteticos_restauracoes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/execucoes/{execucao_id}/avaliacao-risco": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar o detalhe da decisão de risco de uma execução
         * @description Devolve o operando, o valor observado, o resultado e a justificativa de cada critério da decisão de risco já tomada para a execução, sem recalcular nada.
         */
        get: operations["consultar_avaliacao_risco_api_v1_execucoes__execucao_id__avaliacao_risco_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meteorologia/cenarios-sinteticos/{identificador}/ativar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ativar um cenário sintético de contingência
         * @description Ativa, de forma idempotente, o cenário sintético de contingência informado para a área monitorada indicada. O evento resultante tem `proveniencia = sintetico`, nunca combinado com dados `real_inmet`. Exige o cabeçalho `Idempotency-Key` em toda requisição.
         */
        post: operations["ativar_cenario_sintetico_api_v1_meteorologia_cenarios_sinteticos__identificador__ativar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meteorologia/coletas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solicitar uma coleta meteorológica manual
         * @description Solicita, de forma idempotente, uma coleta meteorológica manual para a área informada. Exige o cabeçalho `Idempotency-Key` em toda requisição.
         */
        post: operations["solicitar_coleta_api_v1_meteorologia_coletas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meteorologia/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar os eventos meteorológicos normalizados
         * @description Devolve os eventos meteorológicos já normalizados, do mais recente.
         */
        get: operations["consultar_eventos_api_v1_meteorologia_eventos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meteorologia/sincronizacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar o histórico de sincronizações meteorológicas
         * @description Devolve a última tentativa, a última coleta válida, a próxima consulta estimada e o histórico completo de sincronizações, só com dados persistidos.
         */
        get: operations["consultar_sincronizacoes_api_v1_meteorologia_sincronizacoes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meteorologia/{sincronizacao_id}/nova-tentativa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solicitar uma nova tentativa após indisponibilidade
         * @description Solicita, de forma idempotente, uma nova coleta correlacionada à sincronização de origem informada, sem reabrir nem mutar a sincronização/execução anteriores. Exige o cabeçalho `Idempotency-Key` em toda requisição.
         */
        post: operations["solicitar_nova_tentativa_api_v1_meteorologia__sincronizacao_id__nova_tentativa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prontidao/dependencias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar a prontidão das dependências
         * @description Devolve o estado mais recente de backend, banco de dados, INMET e OpenAI. Backend e banco de dados são recomputados a cada chamada; INMET e OpenAI, na primeira consulta, disparam a verificação em segundo plano e retornam 'verificando'.
         */
        get: operations["consultar_api_v1_prontidao_dependencias_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prontidao/dependencias/{nome}/verificacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solicitar uma nova verificação de prontidão
         * @description Solicita, de forma assíncrona e idempotente, uma nova verificação de INMET ou OpenAI. Exige o cabeçalho `Idempotency-Key` em toda requisição. Backend e banco de dados não aceitam este recurso: já são recomputados a cada `GET`.
         */
        post: operations["verificar_novamente_api_v1_prontidao_dependencias__nome__verificacoes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar todas as versões de regra
         * @description Devolve todas as versões de regra registradas, ativas e substituídas.
         */
        get: operations["consultar_regras_api_v1_regras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regras/{regra_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar uma versão específica de regra
         * @description Devolve uma versão específica de regra pelo seu identificador.
         */
        get: operations["consultar_regra_api_v1_regras__regra_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regras/{regra_id}/ativar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ativar uma nova versão de regra
         * @description Revalida e reexecuta o teste determinístico, e ativa a configuração como nova versão da regra informada, de forma idempotente. Exige o cabeçalho `Idempotency-Key` em toda requisição.
         */
        post: operations["ativar_regra_api_v1_regras__regra_id__ativar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regras/{regra_id}/testar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Testar deterministicamente uma configuração de regra
         * @description Aplica a configuração proposta a cada cenário sintético do tipo de evento, sem persistir nada. Configuração inválida é bloqueada com motivos por campo.
         */
        post: operations["testar_regra_api_v1_regras__regra_id__testar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar a saúde do processo
         * @description Confirma somente que o processo local da API está disponível.
         */
        get: operations["obter_saude_api_v1_saude_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/segurados/padrao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar o segurado sintético padrão
         * @description Devolve o segurado sintético padrão usado na visão de Segurado da demonstração.
         */
        get: operations["consultar_api_v1_segurados_padrao_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErroCampo
         * @description Um erro de validação localizado a um campo específico.
         */
        ErroCampo: {
            /**
             * Campo
             * @description Nome do campo com erro.
             */
            campo: string;
            /**
             * Motivo
             * @description Motivo do erro em português brasileiro.
             */
            motivo: string;
        };
        /**
         * ProblemaAvaliacaoRisco
         * @description Falha da consulta de avaliação de risco, com ocorrência, impacto e próxima ação segura.
         */
        ProblemaAvaliacaoRisco: {
            /**
             * Codigo
             * @description Código estável que identifica o tipo da falha.
             */
            codigo: string;
            /**
             * Correlacao Id
             * @description Identificador único desta ocorrência de falha.
             */
            correlacao_id: string;
            /**
             * Impacto
             * @description Efeito prático da falha para quem consultou o recurso.
             */
            impacto: string;
            /**
             * Ocorrencia
             * @description O que aconteceu, em português brasileiro.
             */
            ocorrencia: string;
            /**
             * Proxima Acao
             * @description Próxima ação segura recomendada para contornar a falha.
             */
            proxima_acao: string;
        };
        /**
         * ProblemaContexto
         * @description Falha da consulta do segurado padrão, com ocorrência, impacto e próxima ação segura.
         */
        ProblemaContexto: {
            /**
             * Codigo
             * @description Código estável que identifica o tipo da falha.
             */
            codigo: string;
            /**
             * Correlacao Id
             * @description Identificador único desta ocorrência de falha.
             */
            correlacao_id: string;
            /**
             * Impacto
             * @description Efeito prático da falha para quem consultou o recurso.
             */
            impacto: string;
            /**
             * Ocorrencia
             * @description O que aconteceu, em português brasileiro.
             */
            ocorrencia: string;
            /**
             * Proxima Acao
             * @description Próxima ação segura recomendada para contornar a falha.
             */
            proxima_acao: string;
        };
        /**
         * ProblemaMeteorologia
         * @description Falha de uma operação meteorológica, com ocorrência, impacto e próxima ação segura.
         */
        ProblemaMeteorologia: {
            /**
             * Codigo
             * @description Código estável que identifica o tipo da falha.
             */
            codigo: string;
            /**
             * Correlacao Id
             * @description Identificador único desta ocorrência de falha.
             */
            correlacao_id: string;
            /**
             * Impacto
             * @description Efeito prático da falha para quem consultou o recurso.
             */
            impacto: string;
            /**
             * Ocorrencia
             * @description O que aconteceu, em português brasileiro.
             */
            ocorrencia: string;
            /**
             * Proxima Acao
             * @description Próxima ação segura recomendada para contornar a falha.
             */
            proxima_acao: string;
        };
        /**
         * ProblemaProntidao
         * @description Falha da operação de prontidão, com ocorrência, impacto e próxima ação segura.
         */
        ProblemaProntidao: {
            /**
             * Codigo
             * @description Código estável que identifica o tipo da falha.
             */
            codigo: string;
            /**
             * Correlacao Id
             * @description Identificador único desta ocorrência de falha.
             */
            correlacao_id: string;
            /**
             * Impacto
             * @description Efeito prático da falha para quem consultou o recurso.
             */
            impacto: string;
            /**
             * Ocorrencia
             * @description O que aconteceu, em português brasileiro.
             */
            ocorrencia: string;
            /**
             * Proxima Acao
             * @description Próxima ação segura recomendada para contornar a falha.
             */
            proxima_acao: string;
        };
        /**
         * ProblemaRegras
         * @description Falha de uma operação de regras, com ocorrência, impacto e próxima ação segura.
         */
        ProblemaRegras: {
            /**
             * Codigo
             * @description Código estável que identifica o tipo da falha.
             */
            codigo: string;
            /**
             * Correlacao Id
             * @description Identificador único desta ocorrência de falha.
             */
            correlacao_id: string;
            /**
             * Erros
             * @description Erros por campo, quando a falha vem de uma configuração inválida.
             */
            erros?: components["schemas"]["ErroCampo"][];
            /**
             * Impacto
             * @description Efeito prático da falha para quem consultou o recurso.
             */
            impacto: string;
            /**
             * Ocorrencia
             * @description O que aconteceu, em português brasileiro.
             */
            ocorrencia: string;
            /**
             * Proxima Acao
             * @description Próxima ação segura recomendada para contornar a falha.
             */
            proxima_acao: string;
        };
        /**
         * ProblemaRestauracao
         * @description Falha da restauração, com ocorrência, impacto e próxima ação segura.
         */
        ProblemaRestauracao: {
            /**
             * Codigo
             * @description Código estável que identifica o tipo da falha.
             */
            codigo: string;
            /**
             * Correlacao Id
             * @description Identificador único desta ocorrência de falha.
             */
            correlacao_id: string;
            /**
             * Impacto
             * @description Efeito prático da falha para quem consultou o recurso.
             */
            impacto: string;
            /**
             * Ocorrencia
             * @description O que aconteceu, em português brasileiro.
             */
            ocorrencia: string;
            /**
             * Proxima Acao
             * @description Próxima ação segura recomendada para contornar a falha.
             */
            proxima_acao: string;
        };
        /**
         * RespostaAvaliacaoRisco
         * @description Snapshot público da avaliação de relevância meteorológica de uma execução.
         */
        RespostaAvaliacaoRisco: {
            /**
             * Criado Em
             * Format: date-time
             * @description Instante RFC 3339 em UTC da avaliação.
             */
            criado_em: string;
            /**
             * Criterios
             * @description Critérios avaliados, na ordem aplicada.
             */
            criterios: components["schemas"]["RespostaCriterio"][];
            /**
             * Evento Id
             * Format: uuid
             * @description Identificador do evento meteorológico avaliado.
             */
            evento_id: string;
            /**
             * Execucao Id
             * Format: uuid
             * @description Identificador da execução avaliada.
             */
            execucao_id: string;
            /**
             * Motivo
             * @description Motivo tipado do resultado.
             */
            motivo: string;
            /**
             * Regra Id
             * @description Identificador da regra aplicada, ou nulo se não havia regra ativa.
             */
            regra_id: string | null;
            /**
             * Regra Versao
             * @description Versão da regra no momento da avaliação, ou nulo se não havia regra ativa.
             */
            regra_versao: number | null;
            /**
             * Relevante
             * @description Se o evento foi considerado relevante.
             */
            relevante: boolean;
        };
        /**
         * RespostaCasoTeste
         * @description Um caso de teste determinístico: o cenário sintético usado e o resultado obtido.
         */
        RespostaCasoTeste: {
            /**
             * Criterios
             * @description Critérios avaliados neste caso.
             */
            criterios: components["schemas"]["RespostaCriterioTeste"][];
            /**
             * Evento Id
             * Format: uuid
             * @description Identificador do evento sintético usado no teste.
             */
            evento_id: string;
            /**
             * Motivo
             * @description Motivo tipado do resultado deste caso.
             */
            motivo: string;
            /**
             * Relevante
             * @description Se o cenário foi considerado relevante pela regra.
             */
            relevante: boolean;
        };
        /**
         * RespostaColetaAceita
         * @description Ack público de uma solicitação de coleta manual aceita ou já registrada.
         */
        RespostaColetaAceita: {
            /**
             * Aceito Em
             * Format: date-time
             * @description Instante RFC 3339 em UTC em que a solicitação foi aceita.
             */
            aceito_em: string;
            /**
             * Estado
             * @description Estado da sincronização no momento da resposta.
             */
            estado: string;
            /**
             * Id
             * Format: uuid
             * @description Identificador da sincronização criada ou já registrada.
             */
            id: string;
            /**
             * Motivo Falha
             * @description Motivo tipado da falha, ou nulo se não houve.
             */
            motivo_falha: string | null;
            /**
             * Registros Validos
             * @description Quantidade de eventos válidos produzidos.
             */
            registros_validos: number;
            /**
             * Requisicao Id
             * Format: uuid
             * @description Identificador de correlação da tentativa.
             */
            requisicao_id: string;
        };
        /**
         * RespostaCriterio
         * @description Um critério avaliado: operando, valor observado, resultado e justificativa.
         */
        RespostaCriterio: {
            /**
             * Atende
             * @description Se o valor observado atende ao critério.
             */
            atende: boolean;
            /**
             * Justificativa
             * @description Explicação em português brasileiro do resultado.
             */
            justificativa: string;
            /**
             * Operando
             * @description O que foi comparado (ex.: área aplicável, intensidade).
             */
            operando: string;
            /**
             * Valor Observado
             * @description Valor observado no evento para este critério.
             */
            valor_observado: string;
        };
        /**
         * RespostaCriterioTeste
         * @description Um critério avaliado no teste determinístico: operando, valor, resultado e justificativa.
         */
        RespostaCriterioTeste: {
            /**
             * Atende
             * @description Se o valor observado atende ao critério.
             */
            atende: boolean;
            /**
             * Justificativa
             * @description Explicação em português brasileiro do resultado.
             */
            justificativa: string;
            /**
             * Operando
             * @description O que foi comparado (ex.: área aplicável, intensidade).
             */
            operando: string;
            /**
             * Valor Observado
             * @description Valor observado no evento para este critério.
             */
            valor_observado: string;
        };
        /**
         * RespostaDependencia
         * @description Estado de prontidão de uma única dependência, pronto para exibição.
         */
        RespostaDependencia: {
            /**
             * Acao Disponivel
             * @description Ação segura disponível dado o estado atual.
             */
            acao_disponivel: string;
            /**
             * Causa
             * @description Causa da indisponibilidade ou degradação, ou nula quando disponível.
             */
            causa: string | null;
            /**
             * Estado
             * @description Estado atual de prontidão da dependência.
             */
            estado: string;
            /**
             * Impacto
             * @description Efeito prático do estado atual para quem consulta.
             */
            impacto: string;
            /**
             * Nome
             * @description Nome canônico da dependência verificada.
             */
            nome: string;
            /**
             * Verificado Em
             * @description Instante RFC 3339 em UTC da última verificação, ou nulo se ainda não houve.
             */
            verificado_em: string | null;
        };
        /**
         * RespostaDependencias
         * @description Resposta pública consolidada das 4 dependências.
         */
        RespostaDependencias: {
            /**
             * Dependencias
             * @description Estado de prontidão de cada uma das 4 dependências monitoradas.
             */
            dependencias: components["schemas"]["RespostaDependencia"][];
        };
        /**
         * RespostaEvento
         * @description Evento meteorológico normalizado, pronto para exibição.
         */
        RespostaEvento: {
            /**
             * Area
             * @description Código IBGE da área onde o evento foi observado.
             */
            area: string;
            /**
             * Id
             * Format: uuid
             * @description Identificador do evento meteorológico.
             */
            id: string;
            /**
             * Instante Observado
             * Format: date-time
             * @description Instante RFC 3339 em UTC em que a medida foi observada.
             */
            instante_observado: string;
            /**
             * Intensidade
             * @description Intensidade normalizada da medida observada.
             */
            intensidade: number;
            /**
             * Periodo Fim
             * Format: date-time
             * @description Término RFC 3339 em UTC do período do evento.
             */
            periodo_fim: string;
            /**
             * Periodo Inicio
             * Format: date-time
             * @description Início RFC 3339 em UTC do período do evento.
             */
            periodo_inicio: string;
            /**
             * Proveniencia
             * @description Origem do evento (`real_inmet` ou `sintetico`).
             */
            proveniencia: string;
            /**
             * Tipo
             * @description Tipo do evento (`chuva_intensa` ou `granizo`).
             */
            tipo: string;
        };
        /**
         * RespostaEventos
         * @description Lista pública de eventos meteorológicos normalizados.
         */
        RespostaEventos: {
            /**
             * Eventos
             * @description Eventos meteorológicos, do mais recente.
             */
            eventos: components["schemas"]["RespostaEvento"][];
        };
        /**
         * RespostaHistoricoSincronizacoes
         * @description Histórico de sincronização, com os marcos exigidos pela consulta de Marina.
         */
        RespostaHistoricoSincronizacoes: {
            /**
             * Proxima Consulta
             * @description Instante RFC 3339 em UTC estimado da próxima coleta automática.
             */
            proxima_consulta: string | null;
            /**
             * Resultados Anteriores
             * @description Histórico completo, da tentativa mais recente para a mais antiga.
             */
            resultados_anteriores: components["schemas"]["RespostaSincronizacao"][];
            /** @description Tentativa mais recente registrada, ou nula se nunca houve nenhuma. */
            ultima_tentativa: components["schemas"]["RespostaSincronizacao"] | null;
            /** @description Última tentativa concluída com sucesso, ou nula se nenhuma concluiu. */
            ultima_valida: components["schemas"]["RespostaSincronizacao"] | null;
        };
        /**
         * RespostaRegra
         * @description Uma versão de regra, para consulta e auditoria.
         */
        RespostaRegra: {
            /**
             * Antecedencia Horas
             * @description Antecedência do alerta preventivo, em horas.
             */
            antecedencia_horas: number;
            /**
             * Apolice Tipo
             * @description Tipo de apólice (`residencial` ou `automovel`).
             */
            apolice_tipo: string;
            /**
             * Area Aplicavel
             * @description Código IBGE da área a que a regra se aplica.
             */
            area_aplicavel: string;
            /**
             * Canal
             * @description Canal de comunicação (`whatsapp`, `email` ou `sms`).
             */
            canal: string;
            /**
             * Cobertura Exigida
             * @description Cobertura que a apólice precisa ter.
             */
            cobertura_exigida: string;
            /**
             * Estado
             * @description Estado da versão (`ativa` ou `substituida`).
             */
            estado: string;
            /**
             * Evento Tipo
             * @description Tipo de evento (`chuva_intensa` ou `granizo`).
             */
            evento_tipo: string;
            /**
             * Id
             * Format: uuid
             * @description Identificador desta versão de regra.
             */
            id: string;
            /**
             * Limiar Meteorologico
             * @description Limiar numérico usado pela regra.
             */
            limiar_meteorologico: number;
            /**
             * Versao
             * @description Número sequencial desta versão da regra.
             */
            versao: number;
        };
        /**
         * RespostaRegras
         * @description Lista pública de versões de regra.
         */
        RespostaRegras: {
            /**
             * Regras
             * @description Versões de regra, mais recentes primeiro.
             */
            regras: components["schemas"]["RespostaRegra"][];
        };
        /**
         * RespostaRestauracao
         * @description Resposta pública de uma restauração concluída.
         */
        RespostaRestauracao: {
            /**
             * Restaurado Em
             * Format: date-time
             * @description Instante RFC 3339 em UTC em que a restauração foi concluída.
             */
            restaurado_em: string;
            /**
             * Status
             * @description Resultado da restauração concluída.
             * @constant
             */
            status: "restaurado";
        };
        /**
         * RespostaSaude
         * @description Resposta pública da disponibilidade do processo backend.
         */
        RespostaSaude: {
            /**
             * Ambiente
             * @description Ambiente de execução do processo.
             * @constant
             */
            ambiente: "educacional";
            /**
             * Status
             * @description Disponibilidade do processo backend.
             * @constant
             */
            status: "disponivel";
        };
        /**
         * RespostaSeguradoPadrao
         * @description Resposta pública do segurado sintético padrão.
         */
        RespostaSeguradoPadrao: {
            /**
             * Id
             * @description Identificador opaco do segurado sintético padrão.
             */
            id: string;
            /**
             * Nome
             * @description Nome do segurado sintético padrão.
             */
            nome: string;
        };
        /**
         * RespostaSincronizacao
         * @description Registro público de uma tentativa de sincronização meteorológica.
         */
        RespostaSincronizacao: {
            /**
             * Area Monitorada Id
             * Format: uuid
             * @description Identificador da área monitorada desta sincronização.
             */
            area_monitorada_id: string;
            /**
             * Estado
             * @description Estado atual da sincronização.
             */
            estado: string;
            /**
             * Finalizado Em
             * @description Instante RFC 3339 em UTC de término, ou nulo se em andamento.
             */
            finalizado_em: string | null;
            /**
             * Id
             * Format: uuid
             * @description Identificador da sincronização.
             */
            id: string;
            /**
             * Iniciado Em
             * Format: date-time
             * @description Instante RFC 3339 em UTC de início da tentativa.
             */
            iniciado_em: string;
            /**
             * Limite Tentativas
             * @description Número máximo de tentativas totais de uma coleta (RESIL-01).
             */
            limite_tentativas: number;
            /**
             * Motivo Falha
             * @description Motivo tipado da falha, ou nulo se não houve.
             */
            motivo_falha: string | null;
            /**
             * Origem
             * @description Origem da tentativa (`automatica` ou `manual`).
             */
            origem: string;
            /**
             * Registros Validos
             * @description Quantidade de eventos válidos produzidos.
             */
            registros_validos: number;
            /**
             * Requisicao Id
             * Format: uuid
             * @description Identificador de correlação da tentativa.
             */
            requisicao_id: string;
            /**
             * Tentativas
             * @description Tentativas individuais desta sincronização, em ordem crescente de número.
             */
            tentativas: components["schemas"]["RespostaTentativa"][];
        };
        /**
         * RespostaTentativa
         * @description Tentativa individual de coleta dentro de uma sincronização com retry (RESIL-02).
         */
        RespostaTentativa: {
            /**
             * Codigo Resultado
             * @description Resultado da tentativa (`sucesso`, `timeout`, `erro_transporte`, `status_erro`).
             */
            codigo_resultado: string;
            /**
             * Finalizado Em
             * Format: date-time
             * @description Instante RFC 3339 em UTC de término da tentativa.
             */
            finalizado_em: string;
            /**
             * Iniciado Em
             * Format: date-time
             * @description Instante RFC 3339 em UTC de início da tentativa.
             */
            iniciado_em: string;
            /**
             * Numero Tentativa
             * @description Número sequencial da tentativa (1 a 3).
             */
            numero_tentativa: number;
        };
        /**
         * RespostaTeste
         * @description Resultado do teste determinístico, um caso por cenário sintético aplicável.
         */
        RespostaTeste: {
            /**
             * Casos
             * @description Casos de teste, um por cenário sintético do tipo de evento da regra.
             */
            casos: components["schemas"]["RespostaCasoTeste"][];
        };
        /**
         * RespostaVerificacaoAceita
         * @description Ack de uma nova verificação aceita para processamento em segundo plano.
         */
        RespostaVerificacaoAceita: {
            /**
             * Aceito Em
             * Format: date-time
             * @description Instante RFC 3339 em UTC em que a nova verificação foi aceita.
             */
            aceito_em: string;
            /**
             * Estado
             * @description Estado da dependência no momento em que a verificação foi aceita.
             */
            estado: string;
            /**
             * Nome
             * @description Nome canônico da dependência cuja verificação foi aceita.
             */
            nome: string;
        };
        /**
         * SolicitacaoAtivarCenarioSintetico
         * @description Corpo da ativação de um cenário sintético: a área monitorada a usar.
         */
        SolicitacaoAtivarCenarioSintetico: {
            /**
             * Area Id
             * Format: uuid
             * @description Identificador da área monitorada onde ativar o cenário.
             */
            area_id: string;
        };
        /**
         * SolicitacaoAtivarRegra
         * @description Configuração de regra proposta, mais a versão esperada para concorrência otimista.
         */
        SolicitacaoAtivarRegra: {
            /**
             * Antecedencia Horas
             * @description Antecedência do alerta preventivo, em horas.
             */
            antecedencia_horas: number;
            /**
             * Apolice Tipo
             * @description Tipo de apólice (`residencial` ou `automovel`).
             */
            apolice_tipo: string;
            /**
             * Area Aplicavel
             * @description Código IBGE da área a que a regra se aplica.
             */
            area_aplicavel: string;
            /**
             * Canal
             * @description Canal de comunicação (`whatsapp`, `email` ou `sms`).
             */
            canal: string;
            /**
             * Cobertura Exigida
             * @description Cobertura que a apólice precisa ter.
             */
            cobertura_exigida: string;
            /**
             * Evento Tipo
             * @description Tipo de evento (`chuva_intensa` ou `granizo`).
             */
            evento_tipo: string;
            /**
             * Limiar Meteorologico
             * @description Limiar numérico usado pela regra.
             */
            limiar_meteorologico: number;
            /**
             * Versao Esperada
             * @description Versão ativa esperada da regra anterior (concorrência otimista, AD-008).
             */
            versao_esperada: number;
        };
        /**
         * SolicitacaoColeta
         * @description Corpo da solicitação de coleta manual: a área monitorada a consultar.
         */
        SolicitacaoColeta: {
            /**
             * Area Id
             * Format: uuid
             * @description Identificador da área monitorada a coletar.
             */
            area_id: string;
        };
        /**
         * SolicitacaoRegra
         * @description Configuração de regra proposta, no formato aceito por `testar`/`ativar`.
         */
        SolicitacaoRegra: {
            /**
             * Antecedencia Horas
             * @description Antecedência do alerta preventivo, em horas.
             */
            antecedencia_horas: number;
            /**
             * Apolice Tipo
             * @description Tipo de apólice (`residencial` ou `automovel`).
             */
            apolice_tipo: string;
            /**
             * Area Aplicavel
             * @description Código IBGE da área a que a regra se aplica.
             */
            area_aplicavel: string;
            /**
             * Canal
             * @description Canal de comunicação (`whatsapp`, `email` ou `sms`).
             */
            canal: string;
            /**
             * Cobertura Exigida
             * @description Cobertura que a apólice precisa ter.
             */
            cobertura_exigida: string;
            /**
             * Evento Tipo
             * @description Tipo de evento (`chuva_intensa` ou `granizo`).
             */
            evento_tipo: string;
            /**
             * Limiar Meteorologico
             * @description Limiar numérico usado pela regra.
             */
            limiar_meteorologico: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    restaurar_api_v1_dados_sinteticos_restauracoes_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados sintéticos restaurados. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaRestauracao"];
                };
            };
            /** @description Restauração recusada sem qualquer mutação. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRestauracao"];
                };
            };
            /** @description Requisição sem o cabeçalho `Idempotency-Key`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRestauracao"];
                };
            };
            /** @description Falha ao concluir a transação de restauração. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRestauracao"];
                };
            };
        };
    };
    consultar_avaliacao_risco_api_v1_execucoes__execucao_id__avaliacao_risco_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execucao_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Avaliação de risco encontrada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaAvaliacaoRisco"];
                };
            };
            /** @description A execução ainda não tem avaliação de risco. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaAvaliacaoRisco"];
                };
            };
            /** @description O identificador da execução não é um UUID válido. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaAvaliacaoRisco"];
                };
            };
        };
    };
    ativar_cenario_sintetico_api_v1_meteorologia_cenarios_sinteticos__identificador__ativar_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                identificador: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitacaoAtivarCenarioSintetico"];
            };
        };
        responses: {
            /** @description Cenário sintético ativado. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaColetaAceita"];
                };
            };
            /** @description Área monitorada desconhecida. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
            /** @description Conflito de idempotência. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
            /** @description Requisição sem o cabeçalho `Idempotency-Key`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
        };
    };
    solicitar_coleta_api_v1_meteorologia_coletas_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitacaoColeta"];
            };
        };
        responses: {
            /** @description Coleta manual aceita e concluída. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaColetaAceita"];
                };
            };
            /** @description Área monitorada desconhecida. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
            /** @description Conflito de idempotência. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
            /** @description Requisição sem o cabeçalho `Idempotency-Key`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
        };
    };
    consultar_eventos_api_v1_meteorologia_eventos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eventos meteorológicos normalizados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaEventos"];
                };
            };
        };
    };
    consultar_sincronizacoes_api_v1_meteorologia_sincronizacoes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Histórico de sincronizações meteorológicas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaHistoricoSincronizacoes"];
                };
            };
        };
    };
    solicitar_nova_tentativa_api_v1_meteorologia__sincronizacao_id__nova_tentativa_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                sincronizacao_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nova tentativa aceita e concluída. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaColetaAceita"];
                };
            };
            /** @description Sincronização de origem ou área monitorada desconhecida. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
            /** @description Conflito de idempotência. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
            /** @description Requisição sem o cabeçalho `Idempotency-Key`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaMeteorologia"];
                };
            };
        };
    };
    consultar_api_v1_prontidao_dependencias_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado de prontidão das 4 dependências. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaDependencias"];
                };
            };
        };
    };
    verificar_novamente_api_v1_prontidao_dependencias__nome__verificacoes_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                nome: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nova verificação aceita e em andamento. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaVerificacaoAceita"];
                };
            };
            /** @description Dependência desconhecida. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaProntidao"];
                };
            };
            /** @description Conflito de idempotência ou verificação já em andamento. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaProntidao"];
                };
            };
            /** @description Cabeçalho ausente ou dependência local sem re-verificação. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaProntidao"];
                };
            };
        };
    };
    consultar_regras_api_v1_regras_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versões de regra. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaRegras"];
                };
            };
        };
    };
    consultar_regra_api_v1_regras__regra_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                regra_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versão de regra encontrada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaRegra"];
                };
            };
            /** @description Regra não encontrada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRegras"];
                };
            };
            /** @description O identificador da regra não é um UUID válido. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRegras"];
                };
            };
        };
    };
    ativar_regra_api_v1_regras__regra_id__ativar_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                regra_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitacaoAtivarRegra"];
            };
        };
        responses: {
            /** @description Nova versão ativada, ou resposta idempotente repetida. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaRegra"];
                };
            };
            /** @description Regra anterior não encontrada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRegras"];
                };
            };
            /** @description Conflito de versão ou de idempotência. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRegras"];
                };
            };
            /** @description Identificador inválido, configuração inválida, cabeçalho `Idempotency-Key` ausente ou nenhum cenário sintético aplicável. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRegras"];
                };
            };
        };
    };
    testar_regra_api_v1_regras__regra_id__testar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                regra_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitacaoRegra"];
            };
        };
        responses: {
            /** @description Resultado do teste determinístico (pode ser vazio). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaTeste"];
                };
            };
            /** @description Identificador inválido ou configuração de regra inválida. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaRegras"];
                };
            };
        };
    };
    obter_saude_api_v1_saude_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saúde do processo confirmada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaSaude"];
                };
            };
        };
    };
    consultar_api_v1_segurados_padrao_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Segurado sintético padrão encontrado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaSeguradoPadrao"];
                };
            };
            /** @description Dados sintéticos ainda não restaurados. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaContexto"];
                };
            };
        };
    };
}
