import { useState } from "react";
import {
  ArrowClockwise, ArrowLeft, Bell, Buildings, CalendarBlank, CaretRight,
  Check, CheckCircle, CloudRain, Database, EnvelopeSimple, Eye, FileText,
  House, Info, Lightning, ListChecks, MagnifyingGlass, MapPin, PaperPlaneTilt,
  PencilSimple, Phone, Question, ShieldCheck, Sparkle, User, Users, Warning,
  WhatsappLogo, Wind, X,
} from "@phosphor-icons/react";

const people = {
  carlos: { id: "carlos", name: "Carlos Eduardo Ferreira", first: "Carlos Eduardo", city: "Salvador/BA", district: "Pituba", address: "Rua das Acácias, 145 — Pituba", cep: "41810-010", phone: "(71) 9 9123-4567", policy: "01.123.456789.00", channel: "WhatsApp", risk: "Alto" },
  mariana: { id: "mariana", name: "Mariana Costa", first: "Mariana", city: "Recife/PE", district: "Boa Viagem", address: "Av. Conselheiro Aguiar, 820 — Boa Viagem", cep: "51011-030", phone: "(81) 9 8442-1108", policy: "01.234.567890.00", channel: "E-mail", risk: "Médio" },
  joao: { id: "joao", name: "João Paulo Andrade", first: "João Paulo", city: "Belo Horizonte/MG", district: "Savassi", address: "Rua Pernambuco, 310 — Savassi", cep: "30130-151", phone: "(31) 9 7442-2601", policy: "01.345.678901.00", channel: "SMS", risk: "Baixo" },
  ana: { id: "ana", name: "Ana Beatriz Carvalho", first: "Ana Beatriz", city: "Curitiba/PR", district: "Água Verde", address: "Rua Pará, 44 — Água Verde", cep: "80620-090", phone: "(41) 9 9330-8821", policy: "01.456.789012.00", channel: "WhatsApp", risk: "Baixo" },
};

const insuredNav = [["overview","Visão geral",House],["alerts","Alertas",Bell],["communications","Comunicados",PaperPlaneTilt],["policies","Minhas apólices",FileText],["profile","Meus dados",User],["faq","Dúvidas frequentes",Question]];
const adminNav = [["admin","Visão geral",House],["event","Eventos climáticos",CloudRain],["rules","Regras de negócio",ShieldCheck],["insureds","Segurados",Users],["messages","Comunicações",PaperPlaneTilt],["sources","Fontes de dados",Database]];
const cx = (...x) => x.filter(Boolean).join(" ");

function Sidebar({ role, page, go }) {
  return <aside className="sidebar">
    <div className="brand"><b>Central Preventiva</b><span>Prever para proteger</span></div>
    <nav>{(role === "admin" ? adminNav : insuredNav).map(([id,label,Icon]) => <button key={id} className={page===id?"active":""} onClick={()=>go(id)}><Icon size={22}/><span>{label}</span></button>)}</nav>
    <div className="sidebar-note"><b><Buildings/> Tudo em simulação</b><span>Ambiente educacional</span><p>Dados sintéticos. Nenhum envio real de mensagens é realizado.</p></div>
  </aside>;
}

function Topbar({ role, changeRole, personId, setPersonId }) {
  return <header className="topbar">
    <label><span>Perfil de acesso</span><div><ShieldCheck/><select value={role} onChange={e=>changeRole(e.target.value)}><option value="admin">Administrador</option><option value="insured">Segurado</option></select></div></label>
    <label className={role==="admin"?"disabled":""}><span>Segurado ativo</span><div><User/><select value={personId} disabled={role==="admin"} onChange={e=>setPersonId(e.target.value)}>{Object.values(people).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>{role==="admin"&&<small>Disponível no perfil Segurado</small>}</label>
    <div className="date"><CalendarBlank/><span><b>22 de agosto de 2026</b><small>Sábado, 08:45</small></span></div>
  </header>;
}

function Weather({ small=false }) { return <div className={cx("weather",small&&"small")}><CloudRain weight="fill"/><Lightning weight="fill"/></div>; }
function Button({ children, secondary=false, ...props }) { return <button className={secondary?"btn secondary":"btn"} {...props}>{children}</button>; }

const tips = ["Revise calhas, ralos e telhados, garantindo o escoamento da água.","Retire objetos de varandas e áreas externas que possam ser levados pelo vento.","Evite estacionar próximo a árvores e estruturas suscetíveis a quedas.","Em caso de alagamento, evite áreas inundadas e não dirija em ruas alagadas."];
function Tips() { return <ul className="tips">{tips.map(t=><li key={t}><CheckCircle weight="fill"/>{t}</li>)}</ul>; }
function Impacts() { return <div className="impacts"><div><CloudRain/><span><b>Chuva intensa</b><small>60 a 100 mm/dia</small></span></div><div><Wind/><span><b>Rajadas de vento</b><small>60 a 80 km/h</small></span></div><div><House/><span><b>Alagamentos</b><small>Risco em áreas baixas</small></span></div></div>; }
function Timeline({ person }) { const rows=[[Sparkle,"Mensagem preventiva gerada por IA","Conteúdo personalizado com base no risco."],[PaperPlaneTilt,"Simulação de envio",`${person.channel} • ${person.phone}`],[CheckCircle,"Mensagem entregue (simulada)","Status: Entregue"],[Eye,"Mensagem visualizada (simulada)","Status: Visualizada"]]; return <div className="timeline">{rows.map(([Icon,title,text],i)=><div key={title}><span><Icon/></span><p><small>22/08/2026 08:{45+i}</small><b>{title}</b><em>{text}</em></p></div>)}</div>; }

function InsuredHome({ person, explain, simulate, go }) {
  return <div className="home-grid"><section className="home-main"><div className="hero"><Weather/><div><small>ALERTA PARA SUA LOCALIDADE</small><h1>Chuva forte e ventos intensos<br/>previstos para {person.city}</h1></div></div><div className="risk"><div><small>NÍVEL DE RISCO</small><b className={person.risk.toLowerCase()}><i/>{person.risk}</b></div><i/><div><small>PERÍODO PREVISTO</small><b><CalendarBlank/>22 a 23 de agosto de 2026</b><span>Das 09h de 22/08 às 23h de 23/08</span></div></div><section className="section"><h3>Impactos esperados para sua região</h3><Impacts/></section><section className="section"><h3>Orientações preventivas para você</h3><Tips/></section><div className="info"><Info/>Este alerta considera sua localização e o perfil do seu seguro para entregar orientações personalizadas e relevantes para você.</div></section><aside className="context"><h2>Seu contexto</h2><ContextItem icon={House} title="Apólice Residencial" text={`Nº ${person.policy}`} sub="Vigência: 10/01/2026 a 10/01/2027"/><ContextItem icon={MapPin} title="Endereço do risco" text={person.address} sub={`${person.city} — ${person.cep}`}/><ContextItem icon={ShieldCheck} title="Coberturas relevantes" text="Incêndio • Vendaval • Danos elétricos" action={()=>go("policies")}/><hr/><h2>Comunicações simuladas</h2><Timeline person={person}/><div className="actions"><Button onClick={simulate}><PaperPlaneTilt/>Simular envio</Button><Button secondary onClick={explain}><FileText/>Ver como a mensagem foi criada</Button></div><small className="fine">Nenhum envio real será realizado.</small></aside></div>;
}
function ContextItem({ icon:Icon,title,text,sub,action }) { return <div className="context-item"><i><Icon/></i><p><b>{title}</b><span>{text}</span>{sub&&<span>{sub}</span>}{action&&<button onClick={action}>Ver detalhes da apólice <CaretRight/></button>}</p></div>; }

function AlertPage({ person, explain, simulate, go }) { return <div className="alert-grid"><aside className="alert-list"><h2>Alertas</h2><h4>Ativos (1)</h4><button className="selected"><Warning/><span><b>Chuva forte e ventos intensos</b><small>{person.city} • Alto</small></span><CaretRight/></button><h4>Anteriores (2)</h4><button><Wind/><span><b>Rajadas de vento</b><small>{person.city} • 15 ago</small></span><CaretRight/></button><button><CloudRain/><span><b>Chuva moderada</b><small>{person.city} • 02 ago</small></span><CaretRight/></button></aside><main className="alert-detail"><div className="hero small"><Weather small/><div><small>ALERTA ATIVO</small><h1>Chuva forte e ventos intensos<br/>{person.city}</h1></div></div><div className="risk compact"><div><small>NÍVEL DE RISCO</small><b className="alto"><i/>Alto</b></div><i/><div><small>PERÍODO PREVISTO</small><b><CalendarBlank/>22 a 23 de agosto de 2026</b></div></div><section className="section"><h3>Impactos esperados para sua região</h3><Impacts/></section><section className="section"><h3>Orientações preventivas personalizadas</h3><Tips/></section><div className="location"><div><h3>Contexto da localização</h3><p><MapPin/>{person.address}</p></div><div><h3>Fonte das informações</h3><p><Database/>INMET • atualizado às 08:30</p></div></div><div className="actions"><Button onClick={simulate}>Simular novo envio</Button><Button secondary onClick={explain}>Como a mensagem foi criada</Button><Button secondary onClick={()=>go("policies")}>Ver apólice</Button></div></main><aside className="alert-time"><h2>Linha do alerta</h2><Timeline person={person}/></aside></div>; }

function PolicyPage({ person, go }) { return <section className="page"><button className="back" onClick={()=>go("alerts")}><ArrowLeft/>Voltar aos alertas</button><div className="title"><i><House/></i><div><h1>Apólice Residencial</h1><p>Nº {person.policy} <b>● Ativa</b></p></div></div><div className="policy-meta"><div><CalendarBlank/><span><b>Vigência</b>10/01/2026 a 10/01/2027</span></div><div><MapPin/><span><b>Endereço do risco</b>{person.address}<small>{person.city} — {person.cep}</small></span></div><div><User/><span><b>Segurado</b>{person.name}</span></div></div><div className="policy-body"><main><h2>Coberturas relevantes para alertas</h2>{[[Wind,"Vendaval"],[Lightning,"Danos elétricos"],[Warning,"Incêndio"],[Buildings,"Impacto de veículos"]].map(([Icon,n])=><div className="coverage" key={n}><Icon/><p><b>{n}</b><span>Proteção relacionada a danos materiais previstos nas condições da apólice.</span></p></div>)}<h3>Como esta apólice é usada nos alertas</h3><p>As regras consideram tipo, vigência, endereço do risco e coberturas relevantes para criar orientações preventivas.</p></main><aside><h2>Preferências de comunicação</h2><ContextItem icon={WhatsappLogo} title="Canal preferido" text={`${person.channel}: ${person.phone}`}/><label className="check"><input type="checkbox" defaultChecked/> Alertas preventivos ativados</label><hr/><h2>Último alerta relacionado</h2><div className="mini-alert"><Weather small/><p><b>Chuva forte e ventos intensos</b><span>22/08/2026 08:45</span><button onClick={()=>go("alerts")}>Ver alerta <CaretRight/></button></p></div></aside></div></section>; }

function SimplePage({ page, person }) { const names={communications:"Comunicados",profile:"Meus dados",faq:"Dúvidas frequentes"}; return <section className="page"><h1>{names[page]}</h1><p className="lead">Área auxiliar da experiência do segurado selecionado.</p>{page==="communications"?<div className="surface"><Timeline person={person}/></div>:page==="profile"?<div className="form-grid"><label>Nome<input value={person.name} readOnly/></label><label>Localização<input value={person.city} readOnly/></label><label>Canal preferido<select defaultValue={person.channel}><option>WhatsApp</option><option>E-mail</option><option>SMS</option></select></label><label>Telefone<input value={person.phone} readOnly/></label></div>:<div className="faq">{["Por que recebi este alerta?","A mensagem foi realmente enviada?","Quais dados a IA utiliza?","Como trocar o segurado simulado?"].map(q=><details key={q}><summary>{q}<CaretRight/></summary><p>Esta prova de conceito utiliza apenas dados sintéticos para demonstrar comunicação preventiva.</p></details>)}</div>}</section>; }

function Flow() { return <div className="flow">{[[Database,"Dados coletados"],[MagnifyingGlass,"Evento identificado"],[ShieldCheck,"Regra aplicada"],[Users,"248 elegíveis"],[PaperPlaneTilt,"Mensagem pronta"]].map(([Icon,t])=><div key={t}><i><Icon/><Check weight="bold"/></i><small>{t}</small></div>)}</div>; }
function AdminHome({ go }) { const events=[[CloudRain,"Chuva forte e eventos intensos","Salvador/BA","Alta"],[CloudRain,"Chuvas intensas","Recife/PE","Média"],[Wind,"Rajadas de vento","Mossoró/RN","Moderada"]]; return <div className="admin-home"><section><h2>Eventos climáticos detectados</h2><p>3 eventos ativos</p><div className="event-list">{events.map(([Icon,t,c,r],i)=><button className={i===0?"selected":""} onClick={()=>go("event")} key={t}><Icon/><span><b>{t}</b><small>{c}</small><em>{r}</em></span><CaretRight/></button>)}</div><div className="event-summary"><h3>Detalhes do evento selecionado</h3><h2>Chuva forte e ventos intensos</h2><p>Salvador/BA • Severidade Alta • Fonte INMET</p><h3>Fluxo de tratamento automático</h3><Flow/><div className="actions"><Button onClick={()=>go("event")}>Analisar evento</Button><Button secondary><ArrowClockwise/>Atualizar dados</Button></div></div></section><div className="map"><span className="state ba">BA</span><span className="state pe">PE</span><span className="state rn">RN</span><i className="pin p1"><CloudRain weight="fill"/></i><i className="pin p2"><CloudRain weight="fill"/></i><i className="pin p3"><Wind weight="fill"/></i><div className="legend"><span><i className="red"/>Alta</span><span><i className="orange"/>Média</span><span><i className="green"/>Baixa</span></div></div></div>; }

function EventPage({ go }) { const conditions=["Localização dentro da área do alerta","Apólice ativa do tipo Residencial","Coberturas relevantes ativas","Severidade do evento é Alta"]; return <section className="page"><button className="back" onClick={()=>go("admin")}><ArrowLeft/>Eventos climáticos</button><div className="event-title"><Weather small/><div><h1>Salvador/BA — Chuva forte</h1><p>Severidade Alta • Fonte INMET • 22 a 23 de agosto</p></div><b><CheckCircle/>Regra aplicada</b></div><div className="analysis"><aside><h2>Evidências meteorológicas</h2><ContextItem icon={CloudRain} title="60 a 100 mm/dia" text="Precipitação prevista"/><ContextItem icon={Wind} title="70 a 90 km/h" text="Rajadas previstas"/><ContextItem icon={MapPin} title="Áreas vulneráveis" text="Risco de alagamento"/><div className="count"><Users/><b>248</b><span>segurados elegíveis</span></div></aside><main><h2>Análise da regra aplicada</h2><div className="rule-head"><i><ShieldCheck/></i><p><b>Chuva intensa — Residencial</b><span>Identifica segurados expostos ao risco.</span></p></div><div className="conditions">{conditions.map(c=><div key={c}><span>{c}</span><b><CheckCircle weight="fill"/>Atendida</b></div>)}</div><h2>Prévia de segurados elegíveis</h2><PeopleTable/><div className="actions end"><Button secondary onClick={()=>go("rules")}><PencilSimple/>Editar regra</Button><Button onClick={()=>go("messages")}><PaperPlaneTilt/>Gerar mensagens</Button></div></main></div></section>; }
function PeopleTable() { return <div className="table">{Object.values(people).map(p=><div key={p.id}><span><User/>{p.name}</span><span>{p.district}</span><span>{p.policy}</span><span>{p.channel}</span></div>)}</div>; }

function RulePage({ notify }) { const [severity,setSeverity]=useState("Alta"),[rain,setRain]=useState("60"); return <section className="page"><h1>Editar regra</h1><p className="lead">Configure as condições e comunicações desta regra preventiva.</p><div className="rule-editor"><main><FormSection number="1" title="Evento"><div className="form-grid three"><label>Tipo de evento<select><option>Chuva intensa</option></select></label><label>Severidade mínima<select value={severity} onChange={e=>setSeverity(e.target.value)}><option>Alta</option><option>Média</option></select></label><label>Precipitação mínima<input value={rain} onChange={e=>setRain(e.target.value)}/></label></div></FormSection><FormSection number="2" title="Público elegível"><div className="form-grid three"><label>Tipo de apólice<select><option>Residencial</option></select></label><label>Status<select><option>Ativa</option></select></label><label>Endereço<select><option>Dentro da área do evento</option></select></label></div></FormSection><FormSection number="3" title="Comunicação"><div className="form-grid three"><label>Antecedência<select><option>Até 24 horas antes</option></select></label><label>Canal<select><option>Preferência do segurado</option></select></label><label>Modelo<select><option>Prevenção e segurança</option></select></label></div><label className="check"><input type="checkbox" defaultChecked/> Exigir verificações de segurança pela IA</label></FormSection><div className="actions end"><Button secondary>Cancelar alterações</Button><Button onClick={notify}><PaperPlaneTilt/>Salvar e testar regra</Button></div></main><aside className="rule-summary"><Eye/><h2>Resumo da regra</h2><p>Quando houver chuva intensa de severidade <b>{severity.toLowerCase()}</b> com precipitação maior ou igual a <b>{rain} mm em 24h</b>, segurados elegíveis receberão uma mensagem preventiva.</p><hr/><span>Estimativa para o evento atual</span><strong>248</strong><small>segurados sintéticos elegíveis</small><b className="valid"><CheckCircle/>Regra válida</b></aside></div></section>; }
function FormSection({number,title,children}) { return <section className="form-section"><h2><i>{number}</i>{title}</h2>{children}</section>; }

function MessagePage({ person, simulate, done, go }) { if(done) return <Results person={person} go={go}/>; return <section className="page messages"><h1>Mensagens preventivas — Chuva forte em Salvador</h1><p className="lead">248 segurados • Regra Chuva intensa — Residencial • Ambiente de simulação</p><div className="message-layout"><aside className="recipients"><h3>Destinatários (248)</h3><div className="search"><MagnifyingGlass/><input placeholder="Buscar destinatário"/></div>{Object.values(people).map((p,i)=><button className={i===0?"selected":""} key={p.id}><User/><span><b>{p.name}</b><small>{p.channel}</small></span><CheckCircle weight="fill"/></button>)}</aside><main className="preview"><h2>Mensagem personalizada</h2><span>Variáveis resolvidas para o destinatário.</span><article><b>Olá, {person.first}.</b><p>A previsão indica chuva forte e ventos intensos em {person.city} entre 22/08 e 23/08.</p><p>Como você tem uma apólice Residencial e mora em {person.district}, preparamos orientações para ajudar a proteger o que é seu.</p><p><b>Nível de risco: Alto</b></p><Tips/><p>Conte com a Central Preventiva.</p></article><button><ArrowClockwise/>Restaurar versão da IA</button></main><aside className="ai"><Sparkle/><h2>Como a IA personalizou</h2><ContextItem icon={CloudRain} title="Evento" text="Chuva forte e ventos intensos"/><ContextItem icon={MapPin} title="Localização" text={person.city}/><ContextItem icon={ShieldCheck} title="Apólice" text={`Residencial — ${person.policy}`}/><ContextItem icon={WhatsappLogo} title="Canal preferido" text={person.channel}/><hr/><h3>Verificações de segurança</h3><Tips/></aside></div><div className="actions end"><Button secondary onClick={()=>go("event")}>Voltar à regra</Button><Button onClick={simulate}><PaperPlaneTilt/>Aprovar e simular envio</Button></div></section>; }

function Results({ person, go }) { const failed={...person,id:"failed",name:"Juliana Costa Almeida",phone:"(71) 90000-0000"}; return <section className="page"><div className="heading-actions"><div><button className="back" onClick={()=>go("admin")}><ArrowLeft/>Voltar</button><h1>Resultado da simulação</h1><p>Chuva forte em Salvador • concluída às 08:50</p></div><Button><FileText/>Exportar relatório</Button></div><div className="stats">{[[PaperPlaneTilt,"248","Geradas"],[CheckCircle,"248","Processadas"],[Eye,"244","Entregues"],[Warning,"4","Falhas"]].map(([Icon,n,t],i)=><div className={i===3?"fail":""} key={t}><Icon/><b>{n}</b><span>{t} (simulado)</span></div>)}</div><div className="results"><main><div className="toolbar"><select><option>Todos os status</option><option>Falha</option></select><select><option>Todos os canais</option></select><div className="search"><MagnifyingGlass/><input placeholder="Buscar destinatário"/></div></div><div className="result-table">{[...Object.values(people),failed].map((p,i)=><button className={i===4?"failed":""} key={p.id}><span><b>{p.name}</b><small>{p.phone}</small></span><span>{p.channel}</span><span>{p.policy}</span><b>{i===4?"Falha":"Entregue"}</b><span>08:50</span></button>)}</div></main><aside className="failure"><Warning/><h2>Detalhes da falha</h2><b>Juliana Costa Almeida</b><p>Número de telefone inválido</p><div>Alerta preventivo: chuva forte prevista para Salvador/BA.</div><Button>Corrigir dado e simular novamente</Button></aside></div></section>; }

function SourcePage() { const [busy,setBusy]=useState(false),[ok,setOk]=useState(false); const retry=()=>{setBusy(true);setTimeout(()=>{setBusy(false);setOk(true)},900)}; return <section className="page"><h1>Fonte meteorológica</h1><p className="lead">Integração pública usada para monitorar eventos externos.</p><div className="source-head"><i><CloudRain/></i><div><h1>INMET</h1><p>Instituto Nacional de Meteorologia</p><b className={ok?"ok":"warn"}>{ok?"Operando normalmente":"Instabilidade detectada"}</b></div><span><small>Última atualização válida</small><b>{ok?"22/08/2026 08:52":"22/08/2026 08:30"}</b></span><span><small>Próxima tentativa</small><b>22/08/2026 09:02</b></span></div><h2>Fluxo de coleta de dados</h2><div className="source-flow">{[[Database,"Conexão"],[MagnifyingGlass,"Consulta"],[ListChecks,"Normalização"],[Bell,"Eventos"]].map(([Icon,t],i)=><div className={!ok&&i===0?"degraded":""} key={t}><Icon/><span><b>{t}</b><small>{!ok&&i===0?"Instabilidade":"Operacional"}</small></span></div>)}</div><div className={cx("source-info",ok&&"success")}><Info/><p><b>{ok?"Dados atualizados com sucesso.":"Estamos usando o último conjunto de dados válido."}</b><span>{ok?"As informações mais recentes já estão disponíveis.":"Novos alertas aguardam a recuperação da fonte."}</span></p></div><div className="source-bottom"><div><h2>Resumo da configuração</h2><dl><div><dt>Provedor</dt><dd>INMET</dd></div><div><dt>Frequência</dt><dd>A cada 15 minutos</dd></div><div><dt>Cobertura</dt><dd>Brasil</dd></div></dl></div><div><h2>Sincronizações recentes</h2><div className="sync"><span>22/08/2026 08:30</span><b>Sucesso</b><span>Dados atualizados</span></div><div className="sync"><span>22/08/2026 08:15</span><b>Sucesso</b><span>Dados atualizados</span></div><div className="sync bad"><span>22/08/2026 08:00</span><b>Falha</b><span>Tempo limite excedido</span></div></div></div><div className="actions"><Button onClick={retry} disabled={busy}><ArrowClockwise className={busy?"spin":""}/>{busy?"Tentando novamente...":"Tentar novamente"}</Button><Button secondary>Usar cenário de demonstração</Button></div></section>; }

function Explain({ person, close, showRules }) { return <div className="overlay"><button aria-label="Fechar" onClick={close}/><aside className="drawer"><button className="close" onClick={close}><X/></button><h1>Como esta mensagem foi criada</h1><p>Veja como usamos dados e regras para gerar uma mensagem preventiva.</p><div className="steps">{[[CloudRain,"Dados meteorológicos",`O INMET detectou chuva forte em ${person.city}.`],[ShieldCheck,"Regra de negócio","Apólice Residencial ativa e endereço na área afetada."],[User,"Personalização por IA",`Nome, localização, coberturas e canal ${person.channel}.`],[PaperPlaneTilt,"Envio simulado","Apenas status e horário foram gerados."]].map(([Icon,t,d],i)=><div key={t}><span>{i+1}</span><i><Icon/></i><p><b>{t}</b><em>{d}</em></p></div>)}</div><h2>Pré-visualização</h2><div className="bubble">Olá, {person.first}. Há previsão de chuva forte em {person.city}. Confira as orientações preventivas.</div><div className="safe"><ShieldCheck/><p><b>Dados que não foram usados</b><span>Documentos, informações financeiras e dados de pagamento.</span></p></div><div className="actions end"><Button secondary onClick={showRules}>Ver regra aplicada</Button><Button onClick={close}>Entendi</Button></div></aside></div>; }
function SimModal({ close, confirm }) { const [checked,setChecked]=useState(true); return <div className="overlay center"><button aria-label="Fechar" onClick={close}/><div className="modal"><button className="close" onClick={close}><X/></button><h2>Simular envio de 248 mensagens?</h2><p>Somente status e horários serão gerados. Nenhuma mensagem real será enviada.</p><div className="channels"><span><WhatsappLogo/>WhatsApp <b>168</b></span><span><EnvelopeSimple/>E-mail <b>61</b></span><span><Phone/>SMS <b>19</b></span></div><dl><div><dt>Evento</dt><dd>Chuva forte em Salvador</dd></div><div><dt>Regra</dt><dd>Chuva intensa — Residencial</dd></div></dl><label className="check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/> Entendo que esta ação é apenas uma simulação.</label><div className="actions end"><Button secondary onClick={close}>Cancelar</Button><Button disabled={!checked} onClick={confirm}>Iniciar simulação</Button></div></div></div>; }
function Toast({ text, close }) { return <div className="toast"><CheckCircle weight="fill"/>{text}<button onClick={close}><X/></button></div>; }

export function App() {
  const [role,setRole]=useState("insured"),[personId,setPersonId]=useState("carlos"),[page,setPage]=useState("overview"),[explain,setExplain]=useState(false),[sim,setSim]=useState(false),[done,setDone]=useState(false),[toast,setToast]=useState("");
  const person=people[personId];
  const changeRole=(r)=>{setRole(r);setPage(r==="admin"?"admin":"overview");setDone(false)};
  const go=(p)=>{setPage(p);if(p!=="messages")setDone(false)};
  const confirm=()=>{setSim(false);setDone(true);setPage(role==="admin"?"messages":"communications");setToast("Simulação concluída com sucesso.")};
  let content;
  if(role==="insured") content=page==="overview"?<InsuredHome person={person} explain={()=>setExplain(true)} simulate={()=>setSim(true)} go={go}/>:page==="alerts"?<AlertPage person={person} explain={()=>setExplain(true)} simulate={()=>setSim(true)} go={go}/>:page==="policies"?<PolicyPage person={person} go={go}/>:<SimplePage page={page} person={person}/>;
  else content=page==="admin"?<AdminHome go={go}/>:page==="event"?<EventPage go={go}/>:page==="rules"?<RulePage notify={()=>setToast("Regra salva e validada com o evento atual.")}/>:page==="messages"?<MessagePage person={person} simulate={()=>setSim(true)} done={done} go={go}/>:page==="sources"?<SourcePage/>:<section className="page"><h1>Segurados sintéticos</h1><p className="lead">Pessoas disponíveis para a demonstração.</p><PeopleTable/></section>;
  return <div className="shell"><Sidebar role={role} page={page} go={go}/><div className="main"><Topbar role={role} changeRole={changeRole} personId={personId} setPersonId={setPersonId}/><main className="screen">{content}</main></div>{explain&&<Explain person={person} close={()=>setExplain(false)} showRules={()=>{setExplain(false);changeRole("admin");setPage("rules")}}/>}{sim&&<SimModal close={()=>setSim(false)} confirm={confirm}/>} {toast&&<Toast text={toast} close={()=>setToast("")}/>}</div>;
}
